//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//

package com.sadad.wsdl.refundsearch._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.sadad.schema.service.refundsearch._1.GetRefundRqType;
import com.sadad.schema.service.refundsearch._1.GetRefundRsType;
import com.sadad.schema.service.refundsearch._1.ListRefundRqType;
import com.sadad.schema.service.refundsearch._1.ListRefundRsType;

@WebService(name = "RefundSearchPort", targetNamespace = "http://sadad.com/wsdl/RefundSearch/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ com.sadad.scm.common._1.ObjectFactory.class, com.sadad.schema.service.refundsearch._1.ObjectFactory.class, com.sadad.scm.error._1.ObjectFactory.class, com.sadad.scm.common.system._1.ObjectFactory.class })
public interface RefundSearchPort
{

	/**
	 * 
	 * @param getRefundRq
	 * @return returns com.sadad.schema.service.refundsearch._1.GetRefundRsType
	 * @throws RefundFault
	 */
	@WebMethod(operationName = "GetRefund", action = "http://sadad.com/EBPP/RefundSearch/GetRefund")
	@WebResult(name = "GetRefundRs", targetNamespace = "http://sadad.com/schema/service/RefundSearch/1.0", partName = "GetRefundRs")
	public GetRefundRsType getRefund(@WebParam(name = "GetRefundRq", targetNamespace = "http://sadad.com/schema/service/RefundSearch/1.0", partName = "GetRefundRq") GetRefundRqType getRefundRq) throws RefundFault;

	/**
	 * 
	 * @param listRefundRq
	 * @return returns com.sadad.schema.service.refundsearch._1.ListRefundRsType
	 * @throws RefundFault
	 */
	@WebMethod(operationName = "ListRefund", action = "http://sadad.com/EBPP/RefundSearch/ListRefund")
	@WebResult(name = "ListRefundRs", targetNamespace = "http://sadad.com/schema/service/RefundSearch/1.0", partName = "ListRefundRs")
	public ListRefundRsType listRefund(@WebParam(name = "ListRefundRq", targetNamespace = "http://sadad.com/schema/service/RefundSearch/1.0", partName = "ListRefundRq") ListRefundRqType listRefundRq) throws RefundFault;

}
