//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccessChannel_SEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccessChannel_SEnum">
 *   &lt;restriction base="{http://www.sadad.com/scm/Common/System/1.0}NC32_SType">
 *     &lt;enumeration value="ATM"/>
 *     &lt;enumeration value="IVR"/>
 *     &lt;enumeration value="KIOSK"/>
 *     &lt;enumeration value="INTERNET"/>
 *     &lt;enumeration value="PORTAL"/>
 *     &lt;enumeration value="BTELLER"/>
 *     &lt;enumeration value="POS"/>
 *     &lt;enumeration value="CAM"/>
 *     &lt;enumeration value="CORP"/>
 *     &lt;enumeration value="CCC"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AccessChannel_SEnum")
@XmlEnum
public enum AccessChannelSEnum {

    ATM,
    IVR,
    KIOSK,
    INTERNET,
    PORTAL,
    BTELLER,
    POS,
    CAM,
    CORP,
    CCC;

    public String value() {
        return name();
    }

    public static AccessChannelSEnum fromValue(String v) {
        return valueOf(v);
    }

}
