//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AccountInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}AccountKey"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillerKey"/>
 *         &lt;element name="BillerName" type="{http://www.sadad.com/scm/Common/System/1.0}Identifier_SType" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}ServiceType"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}Lifecycle" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}AccountSource" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}Beneficiary" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}CreateDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountInfo_Type", propOrder = {
    "accountKey",
    "billerKey",
    "billerName",
    "serviceType",
    "lifecycle",
    "accountSource",
    "beneficiary",
    "createDate"
})
public class AccountInfoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "AccountKey", required = true)
    protected String accountKey;
    @XmlElement(name = "BillerKey", required = true)
    protected String billerKey;
    @XmlElement(name = "BillerName")
    protected String billerName;
    @XmlElement(name = "ServiceType", required = true, defaultValue = "CCRD")
    protected String serviceType;
    @XmlElement(name = "Lifecycle")
    protected AccountLifecycleEnums lifecycle;
    @XmlElement(name = "AccountSource")
    protected AccountSourceEnum accountSource;
    @XmlElement(name = "Beneficiary")
    protected PartyType beneficiary;
    @XmlElement(name = "CreateDate")
    protected XMLGregorianCalendar createDate;

    /**
     * Gets the value of the accountKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountKey() {
        return accountKey;
    }

    /**
     * Sets the value of the accountKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountKey(String value) {
        this.accountKey = value;
    }

    /**
     * Gets the value of the billerKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerKey() {
        return billerKey;
    }

    /**
     * Sets the value of the billerKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerKey(String value) {
        this.billerKey = value;
    }

    /**
     * Gets the value of the billerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerName() {
        return billerName;
    }

    /**
     * Sets the value of the billerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerName(String value) {
        this.billerName = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the lifecycle property.
     * 
     * @return
     *     possible object is
     *     {@link AccountLifecycleEnums }
     *     
     */
    public AccountLifecycleEnums getLifecycle() {
        return lifecycle;
    }

    /**
     * Sets the value of the lifecycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountLifecycleEnums }
     *     
     */
    public void setLifecycle(AccountLifecycleEnums value) {
        this.lifecycle = value;
    }

    /**
     * Gets the value of the accountSource property.
     * 
     * @return
     *     possible object is
     *     {@link AccountSourceEnum }
     *     
     */
    public AccountSourceEnum getAccountSource() {
        return accountSource;
    }

    /**
     * Sets the value of the accountSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountSourceEnum }
     *     
     */
    public void setAccountSource(AccountSourceEnum value) {
        this.accountSource = value;
    }

    /**
     * Gets the value of the beneficiary property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getBeneficiary() {
        return beneficiary;
    }

    /**
     * Sets the value of the beneficiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setBeneficiary(PartyType value) {
        this.beneficiary = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

}
