//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BankFinanicialInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BankFinanicialInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SarieKey" type="{http://www.sadad.com/scm/Common/System/1.0}C64_SType" minOccurs="0"/>
 *         &lt;element name="SADADSuspenseAccount" type="{http://www.sadad.com/scm/Common/System/1.0}C64_SType"/>
 *         &lt;element name="SADADRefundAccount" type="{http://www.sadad.com/scm/Common/System/1.0}C64_SType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankFinanicialInfo_Type", propOrder = {
    "sarieKey",
    "sadadSuspenseAccount",
    "sadadRefundAccount"
})
public class BankFinanicialInfoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SarieKey")
    protected String sarieKey;
    @XmlElement(name = "SADADSuspenseAccount", required = true)
    protected String sadadSuspenseAccount;
    @XmlElement(name = "SADADRefundAccount", required = true)
    protected String sadadRefundAccount;

    /**
     * Gets the value of the sarieKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSarieKey() {
        return sarieKey;
    }

    /**
     * Sets the value of the sarieKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSarieKey(String value) {
        this.sarieKey = value;
    }

    /**
     * Gets the value of the sadadSuspenseAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSADADSuspenseAccount() {
        return sadadSuspenseAccount;
    }

    /**
     * Sets the value of the sadadSuspenseAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSADADSuspenseAccount(String value) {
        this.sadadSuspenseAccount = value;
    }

    /**
     * Gets the value of the sadadRefundAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSADADRefundAccount() {
        return sadadRefundAccount;
    }

    /**
     * Sets the value of the sadadRefundAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSADADRefundAccount(String value) {
        this.sadadRefundAccount = value;
    }

}
