//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.sadad.ebpp.schema.lookup._1.LookupRqType;
import com.sadad.ebpp.schema.lookup._1.LookupRsType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivateBankBranchRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivateBankBranchResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivateBankRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivateBankResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivateBillCategoryRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivateBillCategoryResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivateBillerRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivateBillerResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivatePartnerConfigurationRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivatePartnerConfigurationResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivatePaymentTypeRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ActivatePaymentTypeResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreateBankBranchRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreateBankBranchResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreateBankRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreateBankResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreateBillCategoryRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreateBillCategoryResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreateBillerRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreateBillerResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreatePartnerConfigurationRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreatePartnerConfigurationResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreatePaymentTypeRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.CreatePaymentTypeResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivateBankBranchRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivateBankBranchResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivateBankRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivateBankResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivateBillCategoryRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivateBillCategoryResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivateBillerRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivateBillerResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivatePartnerConfigurationRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivatePartnerConfigurationResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivatePaymentTypeRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeactivatePaymentTypeResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeletePartnerConfigurationRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.DeletePartnerConfigurationResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBankByKeyRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBankByKeyResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBankDetailListRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBankDetailListResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBankListRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBankListResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBillCategoryRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBillCategoryResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBillerByKeyRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBillerByKeyResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBillerDetailListRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBillerDetailListResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBillerListRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBillerListResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBranchCodeRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetBranchCodeResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetFeeServiceProviderDetailsRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetFeeServiceProviderDetailsResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetPartnerConfigurationRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetPartnerConfigurationResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetPaymentTypeRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetPaymentTypeResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetSADADRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetSADADResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetSAMARequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetSAMAResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetSubscribedServiceListRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetSubscribedServiceListResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetSubscribedServiceRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetSubscribedServiceResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.GetSubscriptionToServiceRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.IsSubscribedToConfigurationRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.IsSubscribedToServiceRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ListBankBranchRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ListBankBranchResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ListBillCategoryRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ListBillCategoryResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ListPartnerSummaryRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ListPartnerSummaryResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ListPaymentTypeRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.ListPaymentTypeResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdateBankRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdateBankResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdateBillCategoryRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdateBillCategoryResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdateBillerRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdateBillerResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdatePartnerConfigurationRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdatePartnerConfigurationResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdatePaymentTypeRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdatePaymentTypeResponseType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdateSADADRequestType;
import com.sadad.ebpp.scm.schema.partnerprofileservice._1.UpdateSADADResponseType;


/**
 * This is the base type from which all request and response elements are extended.
 * 
 * <p>Java class for BaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}MessageHeader"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseType", propOrder = {
    "messageHeader"
})
@XmlSeeAlso({
    LookupRqType.class,
    LookupRsType.class,
    CreateBankBranchRequestType.class,
    GetPartnerConfigurationRequestType.class,
    GetBillCategoryResponseType.class,
    UpdateBillCategoryRequestType.class,
    ActivateBillCategoryRequestType.class,
    ActivatePartnerConfigurationResponseType.class,
    GetBillerByKeyResponseType.class,
    GetSAMARequestType.class,
    ListBankBranchResponseType.class,
    CreatePartnerConfigurationRequestType.class,
    ActivateBillCategoryResponseType.class,
    GetBranchCodeRequestType.class,
    UpdateBillerRequestType.class,
    UpdateBankResponseType.class,
    DeletePartnerConfigurationResponseType.class,
    GetSubscribedServiceResponseType.class,
    ActivatePaymentTypeResponseType.class,
    GetSubscribedServiceListResponseType.class,
    GetFeeServiceProviderDetailsResponseType.class,
    GetBillerByKeyRequestType.class,
    ActivateBankBranchRequestType.class,
    CreatePaymentTypeRequestType.class,
    DeactivateBillerResponseType.class,
    ActivateBankRequestType.class,
    ActivatePartnerConfigurationRequestType.class,
    DeactivateBankBranchResponseType.class,
    GetPartnerConfigurationResponseType.class,
    ListBillCategoryResponseType.class,
    ActivatePaymentTypeRequestType.class,
    DeactivatePartnerConfigurationResponseType.class,
    CreateBillCategoryRequestType.class,
    ListPaymentTypeRequestType.class,
    GetBankByKeyResponseType.class,
    ActivateBankResponseType.class,
    UpdatePartnerConfigurationResponseType.class,
    GetBillerListRequestType.class,
    UpdatePartnerConfigurationRequestType.class,
    GetBankListRequestType.class,
    UpdateBillCategoryResponseType.class,
    UpdateSADADResponseType.class,
    GetBillerDetailListResponseType.class,
    ActivateBillerResponseType.class,
    DeactivateBillerRequestType.class,
    UpdatePaymentTypeResponseType.class,
    UpdatePaymentTypeRequestType.class,
    CreateBankBranchResponseType.class,
    ListBankBranchRequestType.class,
    GetBranchCodeResponseType.class,
    DeactivateBillCategoryRequestType.class,
    IsSubscribedToServiceRequestType.class,
    CreateBankResponseType.class,
    ListPartnerSummaryResponseType.class,
    GetFeeServiceProviderDetailsRequestType.class,
    DeactivateBillCategoryResponseType.class,
    GetBillerDetailListRequestType.class,
    DeactivatePaymentTypeRequestType.class,
    ActivateBillerRequestType.class,
    CreateBillerResponseType.class,
    CreateBankRequestType.class,
    DeactivateBankBranchRequestType.class,
    GetBankDetailListResponseType.class,
    DeletePartnerConfigurationRequestType.class,
    GetSADADResponseType.class,
    ListBillCategoryRequestType.class,
    ListPartnerSummaryRequestType.class,
    GetSAMAResponseType.class,
    GetBillCategoryRequestType.class,
    CreatePaymentTypeResponseType.class,
    GetBankDetailListRequestType.class,
    ListPaymentTypeResponseType.class,
    ActivateBankBranchResponseType.class,
    GetPaymentTypeResponseType.class,
    GetBankByKeyRequestType.class,
    DeactivateBankRequestType.class,
    GetSubscriptionToServiceRequestType.class,
    DeactivatePaymentTypeResponseType.class,
    GetPaymentTypeRequestType.class,
    CreateBillerRequestType.class,
    GetBankListResponseType.class,
    DeactivateBankResponseType.class,
    GetSubscribedServiceListRequestType.class,
    CreateBillCategoryResponseType.class,
    IsSubscribedToConfigurationRequestType.class,
    CreatePartnerConfigurationResponseType.class,
    UpdateBillerResponseType.class,
    GetBillerListResponseType.class,
    UpdateSADADRequestType.class,
    GetSADADRequestType.class,
    DeactivatePartnerConfigurationRequestType.class,
    UpdateBankRequestType.class,
    GetSubscribedServiceRequestType.class
})
public abstract class BaseType implements Serializable
{

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "MessageHeader", required = true)
	protected MessageHeaderType messageHeader;

	/**
	 * Gets the value of the messageHeader property.
	 * 
	 * @return possible object is {@link MessageHeaderType }
	 * 
	 */
	public MessageHeaderType getMessageHeader()
	{
		return messageHeader;
	}

	/**
	 * Sets the value of the messageHeader property.
	 * 
	 * @param value
	 *            allowed object is {@link MessageHeaderType }
	 * 
	 */
	public void setMessageHeader(MessageHeaderType value)
	{
		this.messageHeader = value;
	}
}
