//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillCategory_SEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BillCategory_SEnum">
 *   &lt;restriction base="{http://www.sadad.com/scm/Common/System/1.0}NC12_SType">
 *     &lt;enumeration value="Recurring"/>
 *     &lt;enumeration value="CIP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BillCategory_SEnum")
@XmlEnum
public enum BillCategorySEnum {

    @XmlEnumValue("Recurring")
    RECURRING("Recurring"),
    CIP("CIP");
    private final String value;

    BillCategorySEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BillCategorySEnum fromValue(String v) {
        for (BillCategorySEnum c: BillCategorySEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
