//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillAmounts_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillAmounts_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}NetDue"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}PaidAmount"/>
 *         &lt;element name="PaymentRanges" type="{http://www.sadad.com/scm/Common/1.0}Range_CType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillAmounts_Type", propOrder = {
    "netDue",
    "paidAmount",
    "paymentRanges"
})
public class BillAmountsType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "NetDue", required = true)
    protected BigDecimal netDue;
    @XmlElement(name = "PaidAmount", required = true)
    protected BigDecimal paidAmount;
    @XmlElement(name = "PaymentRanges", required = true)
    protected RangeCType paymentRanges;

    /**
     * Gets the value of the netDue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetDue() {
        return netDue;
    }

    /**
     * Sets the value of the netDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetDue(BigDecimal value) {
        this.netDue = value;
    }

    /**
     * Gets the value of the paidAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPaidAmount() {
        return paidAmount;
    }

    /**
     * Sets the value of the paidAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPaidAmount(BigDecimal value) {
        this.paidAmount = value;
    }

    /**
     * Gets the value of the paymentRanges property.
     * 
     * @return
     *     possible object is
     *     {@link RangeCType }
     *     
     */
    public RangeCType getPaymentRanges() {
        return paymentRanges;
    }

    /**
     * Sets the value of the paymentRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeCType }
     *     
     */
    public void setPaymentRanges(RangeCType value) {
        this.paymentRanges = value;
    }

}
