//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * -Represents a Bill in SADAD systems   
 * 
 * <p>Java class for Bill_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bill_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillKey" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}AccountKey" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillerKey"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillCategory"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}ServiceType"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}AmountDue"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}DueDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillCycle" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}GenerationDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}OpenDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}CloseDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}ExpiryDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}MinPartialAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}MaxAdvanceAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}MinAdvanceAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}IsNewCustomer" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}CheckDigit" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillRefInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillLifecycle" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillType" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillStatusCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillPmtStatus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillSummAmt" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bill_Type", propOrder = {
    "billKey",
    "accountKey",
    "billerKey",
    "billCategory",
    "serviceType",
    "amountDue",
    "dueDate",
    "billCycle",
    "generationDate",
    "openDate",
    "closeDate",
    "expiryDate",
    "minPartialAmt",
    "maxAdvanceAmt",
    "minAdvanceAmt",
    "isNewCustomer",
    "checkDigit",
    "billRefInfo",
    "billLifecycle",
    "billType",
    "billStatusCode",
    "billPmtStatus",
    "billSummAmt"
})
public class BillType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "BillKey")
    protected String billKey;
    @XmlElement(name = "AccountKey")
    protected String accountKey;
    @XmlElement(name = "BillerKey", required = true)
    protected String billerKey;
    @XmlElement(name = "BillCategory", required = true)
    protected String billCategory;
    @XmlElement(name = "ServiceType", required = true, defaultValue = "CCRD")
    protected String serviceType;
    @XmlElement(name = "AmountDue", required = true)
    protected BigDecimal amountDue;
    @XmlElement(name = "DueDate")
    protected XMLGregorianCalendar dueDate;
    @XmlElement(name = "BillCycle")
    protected String billCycle;
    @XmlElement(name = "GenerationDate")
    protected XMLGregorianCalendar generationDate;
    @XmlElement(name = "OpenDate")
    protected XMLGregorianCalendar openDate;
    @XmlElement(name = "CloseDate")
    protected XMLGregorianCalendar closeDate;
    @XmlElement(name = "ExpiryDate")
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(name = "MinPartialAmt")
    protected BigDecimal minPartialAmt;
    @XmlElement(name = "MaxAdvanceAmt")
    protected BigDecimal maxAdvanceAmt;
    @XmlElement(name = "MinAdvanceAmt")
    protected BigDecimal minAdvanceAmt;
    @XmlElement(name = "IsNewCustomer")
    protected Boolean isNewCustomer;
    @XmlElement(name = "CheckDigit")
    protected String checkDigit;
    @XmlElement(name = "BillRefInfo")
    protected String billRefInfo;
    @XmlElement(name = "BillLifecycle")
    protected BillLifecycleEnums billLifecycle;
    @XmlElement(name = "BillType")
    protected BillTypeEnums billType;
    @XmlElement(name = "BillStatusCode")
    protected BillStatusCodeType billStatusCode;
    @XmlElement(name = "BillPmtStatus")
    protected List<BillPmtStatusType> billPmtStatus;
    @XmlElement(name = "BillSummAmt")
    protected List<BillSummAmtCType> billSummAmt;

    /**
     * Gets the value of the billKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillKey() {
        return billKey;
    }

    /**
     * Sets the value of the billKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillKey(String value) {
        this.billKey = value;
    }

    /**
     * Gets the value of the accountKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountKey() {
        return accountKey;
    }

    /**
     * Sets the value of the accountKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountKey(String value) {
        this.accountKey = value;
    }

    /**
     * Gets the value of the billerKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerKey() {
        return billerKey;
    }

    /**
     * Sets the value of the billerKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerKey(String value) {
        this.billerKey = value;
    }

    /**
     * Gets the value of the billCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCategory() {
        return billCategory;
    }

    /**
     * Sets the value of the billCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCategory(String value) {
        this.billCategory = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the amountDue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountDue() {
        return amountDue;
    }

    /**
     * Sets the value of the amountDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountDue(BigDecimal value) {
        this.amountDue = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the billCycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCycle() {
        return billCycle;
    }

    /**
     * Sets the value of the billCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCycle(String value) {
        this.billCycle = value;
    }

    /**
     * Gets the value of the generationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGenerationDate() {
        return generationDate;
    }

    /**
     * Sets the value of the generationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGenerationDate(XMLGregorianCalendar value) {
        this.generationDate = value;
    }

    /**
     * Gets the value of the openDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOpenDate() {
        return openDate;
    }

    /**
     * Sets the value of the openDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOpenDate(XMLGregorianCalendar value) {
        this.openDate = value;
    }

    /**
     * Gets the value of the closeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCloseDate() {
        return closeDate;
    }

    /**
     * Sets the value of the closeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCloseDate(XMLGregorianCalendar value) {
        this.closeDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the minPartialAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinPartialAmt() {
        return minPartialAmt;
    }

    /**
     * Sets the value of the minPartialAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinPartialAmt(BigDecimal value) {
        this.minPartialAmt = value;
    }

    /**
     * Gets the value of the maxAdvanceAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxAdvanceAmt() {
        return maxAdvanceAmt;
    }

    /**
     * Sets the value of the maxAdvanceAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxAdvanceAmt(BigDecimal value) {
        this.maxAdvanceAmt = value;
    }

    /**
     * Gets the value of the minAdvanceAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinAdvanceAmt() {
        return minAdvanceAmt;
    }

    /**
     * Sets the value of the minAdvanceAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinAdvanceAmt(BigDecimal value) {
        this.minAdvanceAmt = value;
    }

    /**
     * Gets the value of the isNewCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsNewCustomer() {
        return isNewCustomer;
    }

    /**
     * Sets the value of the isNewCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsNewCustomer(Boolean value) {
        this.isNewCustomer = value;
    }

    /**
     * Gets the value of the checkDigit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckDigit() {
        return checkDigit;
    }

    /**
     * Sets the value of the checkDigit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckDigit(String value) {
        this.checkDigit = value;
    }

    /**
     * Gets the value of the billRefInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillRefInfo() {
        return billRefInfo;
    }

    /**
     * Sets the value of the billRefInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillRefInfo(String value) {
        this.billRefInfo = value;
    }

    /**
     * Gets the value of the billLifecycle property.
     * 
     * @return
     *     possible object is
     *     {@link BillLifecycleEnums }
     *     
     */
    public BillLifecycleEnums getBillLifecycle() {
        return billLifecycle;
    }

    /**
     * Sets the value of the billLifecycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillLifecycleEnums }
     *     
     */
    public void setBillLifecycle(BillLifecycleEnums value) {
        this.billLifecycle = value;
    }

    /**
     * Gets the value of the billType property.
     * 
     * @return
     *     possible object is
     *     {@link BillTypeEnums }
     *     
     */
    public BillTypeEnums getBillType() {
        return billType;
    }

    /**
     * Sets the value of the billType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillTypeEnums }
     *     
     */
    public void setBillType(BillTypeEnums value) {
        this.billType = value;
    }

    /**
     * Gets the value of the billStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BillStatusCodeType }
     *     
     */
    public BillStatusCodeType getBillStatusCode() {
        return billStatusCode;
    }

    /**
     * Sets the value of the billStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillStatusCodeType }
     *     
     */
    public void setBillStatusCode(BillStatusCodeType value) {
        this.billStatusCode = value;
    }

    /**
     * Gets the value of the billPmtStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billPmtStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillPmtStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillPmtStatusType }
     * 
     * 
     */
    public List<BillPmtStatusType> getBillPmtStatus() {
        if (billPmtStatus == null) {
            billPmtStatus = new ArrayList<BillPmtStatusType>();
        }
        return this.billPmtStatus;
    }

    /**
     * Gets the value of the billSummAmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billSummAmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillSummAmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillSummAmtCType }
     * 
     * 
     */
    public List<BillSummAmtCType> getBillSummAmt() {
        if (billSummAmt == null) {
            billSummAmt = new ArrayList<BillSummAmtCType>();
        }
        return this.billSummAmt;
    }

}
