//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillStatusCode_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BillStatusCode_Type">
 *   &lt;restriction base="{http://www.sadad.com/scm/Common/System/1.0}NC32_SType">
 *     &lt;enumeration value="BILL_PAID"/>
 *     &lt;enumeration value="BILL_PARTIAL_PAID"/>
 *     &lt;enumeration value="BILL_OVER_PAID"/>
 *     &lt;enumeration value="BILL_UNPAID"/>
 *     &lt;enumeration value="BILL_DEACTIVE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BillStatusCode_Type")
@XmlEnum
public enum BillStatusCodeType {

    BILL_PAID,
    BILL_PARTIAL_PAID,
    BILL_OVER_PAID,
    BILL_UNPAID,
    BILL_DEACTIVE;

    public String value() {
        return name();
    }

    public static BillStatusCodeType fromValue(String v) {
        return valueOf(v);
    }

}
