//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPaymentDetail_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPaymentDetail_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BillKey" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillType"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillCategory"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}AmountDue"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}MinPartialAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}MaxAdvanceAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}MinAdvanceAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}PaymentAmount" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPaymentDetail_Type", propOrder = {
    "billKey",
    "billType",
    "billCategory",
    "amountDue",
    "minPartialAmt",
    "maxAdvanceAmt",
    "minAdvanceAmt",
    "paymentAmount"
})
public class BillPaymentDetailType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "BillKey")
    protected long billKey;
    @XmlElement(name = "BillType", required = true)
    protected BillTypeEnums billType;
    @XmlElement(name = "BillCategory", required = true)
    protected String billCategory;
    @XmlElement(name = "AmountDue", required = true)
    protected BigDecimal amountDue;
    @XmlElement(name = "MinPartialAmt")
    protected BigDecimal minPartialAmt;
    @XmlElement(name = "MaxAdvanceAmt")
    protected BigDecimal maxAdvanceAmt;
    @XmlElement(name = "MinAdvanceAmt")
    protected BigDecimal minAdvanceAmt;
    @XmlElement(name = "PaymentAmount")
    protected List<PaymentAmountType> paymentAmount;

    /**
     * Gets the value of the billKey property.
     * 
     */
    public long getBillKey() {
        return billKey;
    }

    /**
     * Sets the value of the billKey property.
     * 
     */
    public void setBillKey(long value) {
        this.billKey = value;
    }

    /**
     * Gets the value of the billType property.
     * 
     * @return
     *     possible object is
     *     {@link BillTypeEnums }
     *     
     */
    public BillTypeEnums getBillType() {
        return billType;
    }

    /**
     * Sets the value of the billType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillTypeEnums }
     *     
     */
    public void setBillType(BillTypeEnums value) {
        this.billType = value;
    }

    /**
     * Gets the value of the billCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCategory() {
        return billCategory;
    }

    /**
     * Sets the value of the billCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCategory(String value) {
        this.billCategory = value;
    }

    /**
     * Gets the value of the amountDue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountDue() {
        return amountDue;
    }

    /**
     * Sets the value of the amountDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountDue(BigDecimal value) {
        this.amountDue = value;
    }

    /**
     * Gets the value of the minPartialAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinPartialAmt() {
        return minPartialAmt;
    }

    /**
     * Sets the value of the minPartialAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinPartialAmt(BigDecimal value) {
        this.minPartialAmt = value;
    }

    /**
     * Gets the value of the maxAdvanceAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxAdvanceAmt() {
        return maxAdvanceAmt;
    }

    /**
     * Sets the value of the maxAdvanceAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxAdvanceAmt(BigDecimal value) {
        this.maxAdvanceAmt = value;
    }

    /**
     * Gets the value of the minAdvanceAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinAdvanceAmt() {
        return minAdvanceAmt;
    }

    /**
     * Sets the value of the minAdvanceAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinAdvanceAmt(BigDecimal value) {
        this.minAdvanceAmt = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentAmountType }
     * 
     * 
     */
    public List<PaymentAmountType> getPaymentAmount() {
        if (paymentAmount == null) {
            paymentAmount = new ArrayList<PaymentAmountType>();
        }
        return this.paymentAmount;
    }

}
