//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BillPmtStatus_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPmtStatus_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}PaymentKey"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BNKPTN" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BLRPTN" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}PmtStatusCode"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}CurAmt"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}EffDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPmtStatus_Type", propOrder = {
    "paymentKey",
    "bnkptn",
    "blrptn",
    "pmtStatusCode",
    "curAmt",
    "effDate"
})
public class BillPmtStatusType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "PaymentKey", required = true)
    protected String paymentKey;
    @XmlElement(name = "BNKPTN")
    protected String bnkptn;
    @XmlElement(name = "BLRPTN")
    protected String blrptn;
    @XmlElement(name = "PmtStatusCode", required = true)
    protected PmtStatusCodeType pmtStatusCode;
    @XmlElement(name = "CurAmt", required = true)
    protected BigDecimal curAmt;
    @XmlElement(name = "EffDate")
    protected XMLGregorianCalendar effDate;

    /**
     * Gets the value of the paymentKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentKey() {
        return paymentKey;
    }

    /**
     * Sets the value of the paymentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentKey(String value) {
        this.paymentKey = value;
    }

    /**
     * Gets the value of the bnkptn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBNKPTN() {
        return bnkptn;
    }

    /**
     * Sets the value of the bnkptn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBNKPTN(String value) {
        this.bnkptn = value;
    }

    /**
     * Gets the value of the blrptn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBLRPTN() {
        return blrptn;
    }

    /**
     * Sets the value of the blrptn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBLRPTN(String value) {
        this.blrptn = value;
    }

    /**
     * Gets the value of the pmtStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link PmtStatusCodeType }
     *     
     */
    public PmtStatusCodeType getPmtStatusCode() {
        return pmtStatusCode;
    }

    /**
     * Sets the value of the pmtStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtStatusCodeType }
     *     
     */
    public void setPmtStatusCode(PmtStatusCodeType value) {
        this.pmtStatusCode = value;
    }

    /**
     * Gets the value of the curAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurAmt() {
        return curAmt;
    }

    /**
     * Sets the value of the curAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurAmt(BigDecimal value) {
        this.curAmt = value;
    }

    /**
     * Gets the value of the effDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffDate() {
        return effDate;
    }

    /**
     * Sets the value of the effDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffDate(XMLGregorianCalendar value) {
        this.effDate = value;
    }

}
