//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * To hold additional properties for a Lookup
 * 
 * <p>Java class for Configuration_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Configuration_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Name" type="{http://www.sadad.com/scm/Common/System/1.0}NC100_SType"/>
 *         &lt;element name="Description" type="{http://www.sadad.com/scm/Common/System/1.0}NC100_SType"/>
 *         &lt;element name="Attributes" type="{http://www.sadad.com/scm/Common/1.0}ConfigurationAttribute_Type" maxOccurs="unbounded"/>
 *         &lt;element name="TemplatesData" type="{http://www.sadad.com/scm/Common/1.0}ConfigurationTemplateData_Type" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.sadad.com/scm/Common/1.0}ConfigurationStatus_Enum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Configuration_Type", propOrder = {
    "id",
    "name",
    "description",
    "attributes",
    "templatesData",
    "status"
})
public class ConfigurationType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Id")
    protected long id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Attributes", required = true)
    protected List<ConfigurationAttributeType> attributes;
    @XmlElement(name = "TemplatesData")
    protected ConfigurationTemplateDataType templatesData;
    @XmlElement(name = "Status")
    protected ConfigurationStatusEnum status;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationAttributeType }
     * 
     * 
     */
    public List<ConfigurationAttributeType> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<ConfigurationAttributeType>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the templatesData property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationTemplateDataType }
     *     
     */
    public ConfigurationTemplateDataType getTemplatesData() {
        return templatesData;
    }

    /**
     * Sets the value of the templatesData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationTemplateDataType }
     *     
     */
    public void setTemplatesData(ConfigurationTemplateDataType value) {
        this.templatesData = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationStatusEnum }
     *     
     */
    public ConfigurationStatusEnum getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationStatusEnum }
     *     
     */
    public void setStatus(ConfigurationStatusEnum value) {
        this.status = value;
    }

}
