//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EBPPFileTypes_Enums.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EBPPFileTypes_Enums">
 *   &lt;restriction base="{http://www.sadad.com/scm/Common/System/1.0}NC32_SType">
 *     &lt;enumeration value="AUPLRQ"/>
 *     &lt;enumeration value="ACONRQ"/>
 *     &lt;enumeration value="BUPLRQ"/>
 *     &lt;enumeration value="BUPRRQ"/>
 *     &lt;enumeration value="BCONRQ"/>
 *     &lt;enumeration value="BCORRQ"/>
 *     &lt;enumeration value="PUPLRQ"/>
 *     &lt;enumeration value="PCONRQ"/>
 *     &lt;enumeration value="PNOFRQ"/>
 *     &lt;enumeration value="PNUPRQ"/>
 *     &lt;enumeration value="RUPLRQ"/>
 *     &lt;enumeration value="RCONRQ"/>
 *     &lt;enumeration value="RNOBRQ"/>
 *     &lt;enumeration value="RNOCRQ"/>
 *     &lt;enumeration value="RNUBRQ"/>
 *     &lt;enumeration value="RNUCRQ"/>
 *     &lt;enumeration value="BCUTRQ"/>
 *     &lt;enumeration value="BSPLRQ"/>
 *     &lt;enumeration value="BKRCRQ"/>
 *     &lt;enumeration value="RCUTRQ"/>
 *     &lt;enumeration value="BSRLRQ"/>
 *     &lt;enumeration value="BKRRRQ"/>
 *     &lt;enumeration value="XADDRQ"/>
 *     &lt;enumeration value="XACRRQ"/>
 *     &lt;enumeration value="XADRRQ"/>
 *     &lt;enumeration value="BLRCRQ"/>
 *     &lt;enumeration value="BLTLRQ"/>
 *     &lt;enumeration value="BLRRRQ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EBPPFileTypes_Enums")
@XmlEnum
public enum EBPPFileTypesEnums {


    /**
     * Account Upload
     * 
     */
    AUPLRQ,

    /**
     * Account Upload Confirmation
     * 
     */
    ACONRQ,

    /**
     * Bill Upload
     * 
     */
    BUPLRQ,

    /**
     * Bill Upload Re-generation 
     * 
     */
    BUPRRQ,

    /**
     * Bill Upload Confirmation
     * 
     */
    BCONRQ,

    /**
     * Bill Upload Re-generation confirmation
     * 
     */
    BCORRQ,

    /**
     * Payment Upload
     * 
     */
    PUPLRQ,

    /**
     * Payment Upload Confirmation
     * 
     */
    PCONRQ,

    /**
     * Failover Payment Notification
     * 
     */
    PNOFRQ,

    /**
     * Batch Payment Notification
     * 
     */
    PNUPRQ,

    /**
     * Refund Upload
     * 
     */
    RUPLRQ,

    /**
     * Refund Upload confirmation
     * 
     */
    RCONRQ,

    /**
     * Bulk Refund Notification
     * 
     */
    RNOBRQ,

    /**
     * Bulk Refund Notification Confirmation
     * 
     */
    RNOCRQ,

    /**
     * Batch Refund notification
     * 
     */
    RNUBRQ,

    /**
     * Batch Refund Notification Confirmation
     * 
     */
    RNUCRQ,

    /**
     * Payment Bank cut-off
     * 
     */
    BCUTRQ,

    /**
     * Bank SPL Upload
     * 
     */
    BSPLRQ,

    /**
     * Bank Reconciliation Report
     * 
     */
    BKRCRQ,

    /**
     * Refund Cut-off
     * 
     */
    RCUTRQ,

    /**
     * Bank SRL Upload
     * 
     */
    BSRLRQ,

    /**
     * Bank Refund Reconciliation Report
     * 
     */
    BKRRRQ,

    /**
     * Intra-bank Payment Settlement
     * 
     */
    XADDRQ,

    /**
     * Intra-bank Customer Refund Settlement 
     * 
     */
    XACRRQ,

    /**
     * Intra-bank Biller Account Refund Settlement 
     * 
     */
    XADRRQ,

    /**
     * Biller Reconciliation Report - Payments
     * 
     */
    BLRCRQ,

    /**
     * Biller SPL Log
     * 
     */
    BLTLRQ,

    /**
     * Biller Reconciliation Report - Refunds
     * 
     */
    BLRRRQ;

    public String value() {
        return name();
    }

    public static EBPPFileTypesEnums fromValue(String v) {
        return valueOf(v);
    }

}
