//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnterpriseDataEvent_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnterpriseDataEvent_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}EventKey"/>
 *         &lt;element name="EventAttributes" type="{http://www.sadad.com/scm/Common/1.0}EventAttributes_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnterpriseDataEvent_Type", propOrder = {
    "eventKey",
    "eventAttributes"
})
public class EnterpriseDataEventType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EventKey", required = true)
    protected String eventKey;
    @XmlElement(name = "EventAttributes")
    protected EventAttributesType eventAttributes;

    /**
     * 
     * 						This will be populated according to the Event Type as follows:
     * 						AccessChannelList: System Access Channels List Event
     * 						DisctrictCodeList: System District Codes List Event
     * 						PaymentMethodList: System Payment Methods List Event
     * 						BillerServiceCodes: Fee Service Provider Service Codes Event
     * 						PartnerIdentity: Partner Identity Event
     * 						ParnerSubscription: Partner Service Subscription Event
     * 						BankBarachCodes: Bank Branch Codes Even
     * 
     * 						Occurnces:
     * 						Create, Update Status
     * 					
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventKey() {
        return eventKey;
    }

    /**
     * Sets the value of the eventKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventKey(String value) {
        this.eventKey = value;
    }

    /**
     * Gets the value of the eventAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link EventAttributesType }
     *     
     */
    public EventAttributesType getEventAttributes() {
        return eventAttributes;
    }

    /**
     * Sets the value of the eventAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventAttributesType }
     *     
     */
    public void setEventAttributes(EventAttributesType value) {
        this.eventAttributes = value;
    }

}
