//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.sadad.scm.common.system._1.CurrencyTypeEnums;


/**
 * Instruction Type
 * 
 * <p>Java class for Instruction_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Instruction_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}InstructionID"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BankKey"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}CrDr"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}Currency"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}Amount"/>
 *         &lt;element name="BankStatusCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="BankStatusDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}InstructionStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Instruction_Type", propOrder = {
    "instructionID",
    "bankKey",
    "crDr",
    "currency",
    "amount",
    "bankStatusCode",
    "bankStatusDesc",
    "instructionStatus"
})
public class InstructionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "InstructionID", required = true)
    protected String instructionID;
    @XmlElement(name = "BankKey", required = true)
    protected String bankKey;
    @XmlElement(name = "CrDr", required = true)
    protected TransactionTypeEnum crDr;
    @XmlElement(name = "Currency", required = true)
    protected CurrencyTypeEnums currency;
    @XmlElement(name = "Amount", required = true)
    protected BigDecimal amount;
    @XmlElement(name = "BankStatusCode")
    protected Long bankStatusCode;
    @XmlElement(name = "BankStatusDesc")
    protected String bankStatusDesc;
    @XmlElement(name = "InstructionStatus", required = true)
    protected InstructionStatusCodeEnums instructionStatus;

    /**
     * Gets the value of the instructionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructionID() {
        return instructionID;
    }

    /**
     * Sets the value of the instructionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructionID(String value) {
        this.instructionID = value;
    }

    /**
     * Gets the value of the bankKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankKey() {
        return bankKey;
    }

    /**
     * Sets the value of the bankKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankKey(String value) {
        this.bankKey = value;
    }

    /**
     * Gets the value of the crDr property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionTypeEnum }
     *     
     */
    public TransactionTypeEnum getCrDr() {
        return crDr;
    }

    /**
     * Sets the value of the crDr property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionTypeEnum }
     *     
     */
    public void setCrDr(TransactionTypeEnum value) {
        this.crDr = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyTypeEnums }
     *     
     */
    public CurrencyTypeEnums getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyTypeEnums }
     *     
     */
    public void setCurrency(CurrencyTypeEnums value) {
        this.currency = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the bankStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBankStatusCode() {
        return bankStatusCode;
    }

    /**
     * Sets the value of the bankStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBankStatusCode(Long value) {
        this.bankStatusCode = value;
    }

    /**
     * Gets the value of the bankStatusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankStatusDesc() {
        return bankStatusDesc;
    }

    /**
     * Sets the value of the bankStatusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankStatusDesc(String value) {
        this.bankStatusDesc = value;
    }

    /**
     * Gets the value of the instructionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link InstructionStatusCodeEnums }
     *     
     */
    public InstructionStatusCodeEnums getInstructionStatus() {
        return instructionStatus;
    }

    /**
     * Sets the value of the instructionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstructionStatusCodeEnums }
     *     
     */
    public void setInstructionStatus(InstructionStatusCodeEnums value) {
        this.instructionStatus = value;
    }

}
