//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * -Represents a Service MQ End Point
 * 
 * <p>Java class for MQEndPoint_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MQEndPoint_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sadad.com/scm/Common/1.0}BaseEndPoint_Type">
 *       &lt;sequence>
 *         &lt;element name="RequestQ" type="{http://www.sadad.com/scm/Common/System/1.0}C255_SType"/>
 *         &lt;element name="RequestQMGR" type="{http://www.sadad.com/scm/Common/System/1.0}C255_SType"/>
 *         &lt;element name="ResponseQ" type="{http://www.sadad.com/scm/Common/System/1.0}C255_SType"/>
 *         &lt;element name="ResponseQMGR" type="{http://www.sadad.com/scm/Common/System/1.0}C255_SType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MQEndPoint_Type", propOrder = {
    "requestQ",
    "requestQMGR",
    "responseQ",
    "responseQMGR"
})
public class MQEndPointType
    extends BaseEndPointType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "RequestQ", required = true)
    protected String requestQ;
    @XmlElement(name = "RequestQMGR", required = true)
    protected String requestQMGR;
    @XmlElement(name = "ResponseQ", required = true)
    protected String responseQ;
    @XmlElement(name = "ResponseQMGR", required = true)
    protected String responseQMGR;

    /**
     * Gets the value of the requestQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestQ() {
        return requestQ;
    }

    /**
     * Sets the value of the requestQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestQ(String value) {
        this.requestQ = value;
    }

    /**
     * Gets the value of the requestQMGR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestQMGR() {
        return requestQMGR;
    }

    /**
     * Sets the value of the requestQMGR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestQMGR(String value) {
        this.requestQMGR = value;
    }

    /**
     * Gets the value of the responseQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseQ() {
        return responseQ;
    }

    /**
     * Sets the value of the responseQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseQ(String value) {
        this.responseQ = value;
    }

    /**
     * Gets the value of the responseQMGR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseQMGR() {
        return responseQMGR;
    }

    /**
     * Sets the value of the responseQMGR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseQMGR(String value) {
        this.responseQMGR = value;
    }

}
