//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * To hold additional properties for a Lookup
 * 
 * <p>Java class for PartnerConfiguration_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartnerConfiguration_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConfigurationId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}ConfigurationName"/>
 *         &lt;element name="Template" type="{http://www.sadad.com/scm/Common/1.0}PartnerConfigurationTemplate_Type" minOccurs="0"/>
 *         &lt;element name="Attributes" type="{http://www.sadad.com/scm/Common/1.0}PartnerConfigurationAttributes_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerConfiguration_Type", propOrder = {
    "configurationId",
    "configurationName",
    "template",
    "attributes"
})
public class PartnerConfigurationType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ConfigurationId")
    protected Long configurationId;
    @XmlElement(name = "ConfigurationName", required = true)
    protected String configurationName;
    @XmlElement(name = "Template")
    protected PartnerConfigurationTemplateType template;
    @XmlElement(name = "Attributes")
    protected PartnerConfigurationAttributesType attributes;

    /**
     * Gets the value of the configurationId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConfigurationId() {
        return configurationId;
    }

    /**
     * Sets the value of the configurationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConfigurationId(Long value) {
        this.configurationId = value;
    }

    /**
     * Gets the value of the configurationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationName() {
        return configurationName;
    }

    /**
     * Sets the value of the configurationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationName(String value) {
        this.configurationName = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link PartnerConfigurationTemplateType }
     *     
     */
    public PartnerConfigurationTemplateType getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnerConfigurationTemplateType }
     *     
     */
    public void setTemplate(PartnerConfigurationTemplateType value) {
        this.template = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link PartnerConfigurationAttributesType }
     *     
     */
    public PartnerConfigurationAttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnerConfigurationAttributesType }
     *     
     */
    public void setAttributes(PartnerConfigurationAttributesType value) {
        this.attributes = value;
    }

}
