//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentIdType_Enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentIdType_Enum">
 *   &lt;restriction base="{http://www.sadad.com/scm/Common/System/1.0}NC8_SType">
 *     &lt;enumeration value="SPTN"/>
 *     &lt;enumeration value="BNKPTN"/>
 *     &lt;enumeration value="BNKRVL"/>
 *     &lt;enumeration value="BLRPTN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PaymentIdType_Enum")
@XmlEnum
public enum PaymentIdTypeEnum {

    SPTN,
    BNKPTN,
    BNKRVL,
    BLRPTN;

    public String value() {
        return name();
    }

    public static PaymentIdTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
