//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}Payment"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}PaymentReference"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}PaymentExtn"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentInfo_Type", propOrder = {
    "payment",
    "paymentReference",
    "paymentExtn"
})
public class PaymentInfoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Payment", required = true)
    protected PaymentType payment;
    @XmlElement(name = "PaymentReference", required = true)
    protected PaymentReferenceType paymentReference;
    @XmlElement(name = "PaymentExtn", required = true)
    protected PaymentExtnType paymentExtn;

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentType }
     *     
     */
    public PaymentType getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentType }
     *     
     */
    public void setPayment(PaymentType value) {
        this.payment = value;
    }

    /**
     * Gets the value of the paymentReference property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentReferenceType }
     *     
     */
    public PaymentReferenceType getPaymentReference() {
        return paymentReference;
    }

    /**
     * Sets the value of the paymentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentReferenceType }
     *     
     */
    public void setPaymentReference(PaymentReferenceType value) {
        this.paymentReference = value;
    }

    /**
     * Gets the value of the paymentExtn property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentExtnType }
     *     
     */
    public PaymentExtnType getPaymentExtn() {
        return paymentExtn;
    }

    /**
     * Sets the value of the paymentExtn property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentExtnType }
     *     
     */
    public void setPaymentExtn(PaymentExtnType value) {
        this.paymentExtn = value;
    }

}
