//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriorityType_Enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PriorityType_Enum">
 *   &lt;restriction base="{http://www.sadad.com/scm/Common/System/1.0}NC32_SType">
 *     &lt;enumeration value="HIGH"/>
 *     &lt;enumeration value="NORMAL"/>
 *     &lt;enumeration value="LOW"/>
 *     &lt;enumeration value="HOLD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PriorityType_Enum")
@XmlEnum
public enum PriorityTypeEnum {

    HIGH,
    NORMAL,
    LOW,
    HOLD;

    public String value() {
        return name();
    }

    public static PriorityTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
