//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SADADFinanicialInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SADADFinanicialInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SADADCurrentAccount" type="{http://www.sadad.com/scm/Common/1.0}FinancialAccount_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SADADFinanicialInfo_Type", propOrder = {
    "sadadCurrentAccount"
})
public class SADADFinanicialInfoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SADADCurrentAccount", required = true)
    protected FinancialAccountType sadadCurrentAccount;

    /**
     * Gets the value of the sadadCurrentAccount property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialAccountType }
     *     
     */
    public FinancialAccountType getSADADCurrentAccount() {
        return sadadCurrentAccount;
    }

    /**
     * Sets the value of the sadadCurrentAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialAccountType }
     *     
     */
    public void setSADADCurrentAccount(FinancialAccountType value) {
        this.sadadCurrentAccount = value;
    }

}
