//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.common._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceType_SEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceType_SEnum">
 *   &lt;restriction base="{http://www.sadad.com/scm/Common/System/1.0}NC4_SType">
 *     &lt;enumeration value="CIP"/>
 *     &lt;enumeration value="ELCT"/>
 *     &lt;enumeration value="PHON"/>
 *     &lt;enumeration value="GSM"/>
 *     &lt;enumeration value="LLIN"/>
 *     &lt;enumeration value="INSR"/>
 *     &lt;enumeration value="BKSV"/>
 *     &lt;enumeration value="GOVT"/>
 *     &lt;enumeration value="MED"/>
 *     &lt;enumeration value="CCRD"/>
 *     &lt;enumeration value="UTIL"/>
 *     &lt;enumeration value="PCIN"/>
 *     &lt;enumeration value="EXAM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ServiceType_SEnum")
@XmlEnum
public enum ServiceTypeSEnum {

    CIP,
    ELCT,
    PHON,
    GSM,
    LLIN,
    INSR,
    BKSV,
    GOVT,
    MED,
    CCRD,
    UTIL,
    PCIN,
    EXAM;

    public String value() {
        return name();
    }

    public static ServiceTypeSEnum fromValue(String v) {
        return valueOf(v);
    }

}
