//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.ebpp.schema.lookup._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				- the CriteriaKey should be one of the following strings
 * 					"ServiceMsgType" to be used in MESSAGE_CODES Lookup.
 * 				- the CriteriaValue should be on the following 
 * 					in case of CriteriaKey is "ServiceMsgType" the CriteriaValue Should be ["SOAP" or "XML"]					 
 * 			
 * 
 * <p>Java class for Criteria_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Criteria_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CriteriaKey" type="{http://www.sadad.com/scm/Common/System/1.0}C32_SType"/>
 *         &lt;element name="CriteriaValue" type="{http://www.sadad.com/scm/Common/System/1.0}C32_SType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Criteria_Type", propOrder = {
    "criteriaKey",
    "criteriaValue"
})
public class CriteriaType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CriteriaKey", required = true)
    protected String criteriaKey;
    @XmlElement(name = "CriteriaValue", required = true)
    protected String criteriaValue;

    /**
     * Gets the value of the criteriaKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCriteriaKey() {
        return criteriaKey;
    }

    /**
     * Sets the value of the criteriaKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCriteriaKey(String value) {
        this.criteriaKey = value;
    }

    /**
     * Gets the value of the criteriaValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCriteriaValue() {
        return criteriaValue;
    }

    /**
     * Sets the value of the criteriaValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCriteriaValue(String value) {
        this.criteriaValue = value;
    }

}
