//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.sadad.ebpp.scm.schema.customer._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.sadad.scm.common._1.AccountIdType;


/**
 *  Status response from each account
 * 			
 * 
 * <p>Java class for AccountAssnInqStatus_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountAssnInqStatus_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}RecordNumber"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}Account"/>
 *         &lt;element ref="{http://www.sadad.com/EBPP/scm/schema/Customer/1.0}IsInProfile"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountAssnInqStatus_Type", propOrder = {
    "recordNumber",
    "account",
    "isInProfile"
})
@XmlSeeAlso({
    AccountAssnStatusType.class
})
public class AccountAssnInqStatusType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "RecordNumber", namespace = "http://www.sadad.com/scm/Common/1.0")
    protected long recordNumber;
    @XmlElement(name = "Account", namespace = "http://www.sadad.com/scm/Common/1.0", required = true)
    protected AccountIdType account;
    @XmlElement(name = "IsInProfile")
    protected boolean isInProfile;

    /**
     * Gets the value of the recordNumber property.
     * 
     */
    public long getRecordNumber() {
        return recordNumber;
    }

    /**
     * Sets the value of the recordNumber property.
     * 
     */
    public void setRecordNumber(long value) {
        this.recordNumber = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link AccountIdType }
     *     
     */
    public AccountIdType getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountIdType }
     *     
     */
    public void setAccount(AccountIdType value) {
        this.account = value;
    }

    /**
     * Gets the value of the isInProfile property.
     * 
     */
    public boolean isIsInProfile() {
        return isInProfile;
    }

    /**
     * Sets the value of the isInProfile property.
     * 
     */
    public void setIsInProfile(boolean value) {
        this.isInProfile = value;
    }

}
