//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.sadad.ebpp.scm.schema.customer._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.sadad.scm.error._1.FaultType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sadad.ebpp.scm.schema.customer._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustProfileAssnRq_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "CustProfileAssnRq");
    private final static QName _CustProfileDisassnRs_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "CustProfileDisassnRs");
    private final static QName _CustProfileDisassnRq_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "CustProfileDisassnRq");
    private final static QName _AccountAssnInqStatus_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "AccountAssnInqStatus");
    private final static QName _CustomerFault_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "CustomerFault");
    private final static QName _CustProfileAssnRs_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "CustProfileAssnRs");
    private final static QName _ListByAccountRq_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "ListByAccountRq");
    private final static QName _ListByAccountRs_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "ListByAccountRs");
    private final static QName _ActivateRq_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "ActivateRq");
    private final static QName _CustProfileInqRq_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "CustProfileInqRq");
    private final static QName _ActivateRs_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "ActivateRs");
    private final static QName _CustProfileInqRs_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "CustProfileInqRs");
    private final static QName _GetByKeyRs_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "GetByKeyRs");
    private final static QName _GetByKeyRq_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "GetByKeyRq");
    private final static QName _AccountAssnStatus_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "AccountAssnStatus");
    private final static QName _DeactivateRs_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "DeactivateRs");
    private final static QName _DeactivateRq_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "DeactivateRq");
    private final static QName _AccountDisassnStatus_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "AccountDisassnStatus");
    private final static QName _IsInProfile_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "IsInProfile");
    private final static QName _ListByBillRs_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "ListByBillRs");
    private final static QName _ListByBillRq_QNAME = new QName("http://www.sadad.com/EBPP/scm/schema/Customer/1.0", "ListByBillRq");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sadad.ebpp.scm.schema.customer._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccountAssnStatusType }
     * 
     */
    public AccountAssnStatusType createAccountAssnStatusType() {
        return new AccountAssnStatusType();
    }

    /**
     * Create an instance of {@link GetByKeyRsType }
     * 
     */
    public GetByKeyRsType createGetByKeyRsType() {
        return new GetByKeyRsType();
    }

    /**
     * Create an instance of {@link GetByKeyRqType }
     * 
     */
    public GetByKeyRqType createGetByKeyRqType() {
        return new GetByKeyRqType();
    }

    /**
     * Create an instance of {@link CustProfileInqRsType }
     * 
     */
    public CustProfileInqRsType createCustProfileInqRsType() {
        return new CustProfileInqRsType();
    }

    /**
     * Create an instance of {@link CustProfileAssnRsType }
     * 
     */
    public CustProfileAssnRsType createCustProfileAssnRsType() {
        return new CustProfileAssnRsType();
    }

    /**
     * Create an instance of {@link CustProfileInqRqType }
     * 
     */
    public CustProfileInqRqType createCustProfileInqRqType() {
        return new CustProfileInqRqType();
    }

    /**
     * Create an instance of {@link DeactivateRsType }
     * 
     */
    public DeactivateRsType createDeactivateRsType() {
        return new DeactivateRsType();
    }

    /**
     * Create an instance of {@link DeactivateRqType }
     * 
     */
    public DeactivateRqType createDeactivateRqType() {
        return new DeactivateRqType();
    }

    /**
     * Create an instance of {@link CustProfileAssnRqType }
     * 
     */
    public CustProfileAssnRqType createCustProfileAssnRqType() {
        return new CustProfileAssnRqType();
    }

    /**
     * Create an instance of {@link ActivateRqType }
     * 
     */
    public ActivateRqType createActivateRqType() {
        return new ActivateRqType();
    }

    /**
     * Create an instance of {@link ActivateRsType }
     * 
     */
    public ActivateRsType createActivateRsType() {
        return new ActivateRsType();
    }

    /**
     * Create an instance of {@link ListByAccountRqType }
     * 
     */
    public ListByAccountRqType createListByAccountRqType() {
        return new ListByAccountRqType();
    }

    /**
     * Create an instance of {@link AccountAssnInqStatusType }
     * 
     */
    public AccountAssnInqStatusType createAccountAssnInqStatusType() {
        return new AccountAssnInqStatusType();
    }

    /**
     * Create an instance of {@link ListByBillRqType }
     * 
     */
    public ListByBillRqType createListByBillRqType() {
        return new ListByBillRqType();
    }

    /**
     * Create an instance of {@link ListByAccountRsType }
     * 
     */
    public ListByAccountRsType createListByAccountRsType() {
        return new ListByAccountRsType();
    }

    /**
     * Create an instance of {@link CustProfileDisassnRsType }
     * 
     */
    public CustProfileDisassnRsType createCustProfileDisassnRsType() {
        return new CustProfileDisassnRsType();
    }

    /**
     * Create an instance of {@link ListByBillRsType }
     * 
     */
    public ListByBillRsType createListByBillRsType() {
        return new ListByBillRsType();
    }

    /**
     * Create an instance of {@link CustProfileDisassnRqType }
     * 
     */
    public CustProfileDisassnRqType createCustProfileDisassnRqType() {
        return new CustProfileDisassnRqType();
    }

    /**
     * Create an instance of {@link AccountsType }
     * 
     */
    public AccountsType createAccountsType() {
        return new AccountsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustProfileAssnRqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "CustProfileAssnRq")
    public JAXBElement<CustProfileAssnRqType> createCustProfileAssnRq(CustProfileAssnRqType value) {
        return new JAXBElement<CustProfileAssnRqType>(_CustProfileAssnRq_QNAME, CustProfileAssnRqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustProfileDisassnRsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "CustProfileDisassnRs")
    public JAXBElement<CustProfileDisassnRsType> createCustProfileDisassnRs(CustProfileDisassnRsType value) {
        return new JAXBElement<CustProfileDisassnRsType>(_CustProfileDisassnRs_QNAME, CustProfileDisassnRsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustProfileDisassnRqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "CustProfileDisassnRq")
    public JAXBElement<CustProfileDisassnRqType> createCustProfileDisassnRq(CustProfileDisassnRqType value) {
        return new JAXBElement<CustProfileDisassnRqType>(_CustProfileDisassnRq_QNAME, CustProfileDisassnRqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountAssnInqStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "AccountAssnInqStatus")
    public JAXBElement<AccountAssnInqStatusType> createAccountAssnInqStatus(AccountAssnInqStatusType value) {
        return new JAXBElement<AccountAssnInqStatusType>(_AccountAssnInqStatus_QNAME, AccountAssnInqStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "CustomerFault")
    public JAXBElement<FaultType> createCustomerFault(FaultType value) {
        return new JAXBElement<FaultType>(_CustomerFault_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustProfileAssnRsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "CustProfileAssnRs")
    public JAXBElement<CustProfileAssnRsType> createCustProfileAssnRs(CustProfileAssnRsType value) {
        return new JAXBElement<CustProfileAssnRsType>(_CustProfileAssnRs_QNAME, CustProfileAssnRsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListByAccountRqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "ListByAccountRq")
    public JAXBElement<ListByAccountRqType> createListByAccountRq(ListByAccountRqType value) {
        return new JAXBElement<ListByAccountRqType>(_ListByAccountRq_QNAME, ListByAccountRqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListByAccountRsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "ListByAccountRs")
    public JAXBElement<ListByAccountRsType> createListByAccountRs(ListByAccountRsType value) {
        return new JAXBElement<ListByAccountRsType>(_ListByAccountRs_QNAME, ListByAccountRsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateRqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "ActivateRq")
    public JAXBElement<ActivateRqType> createActivateRq(ActivateRqType value) {
        return new JAXBElement<ActivateRqType>(_ActivateRq_QNAME, ActivateRqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustProfileInqRqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "CustProfileInqRq")
    public JAXBElement<CustProfileInqRqType> createCustProfileInqRq(CustProfileInqRqType value) {
        return new JAXBElement<CustProfileInqRqType>(_CustProfileInqRq_QNAME, CustProfileInqRqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateRsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "ActivateRs")
    public JAXBElement<ActivateRsType> createActivateRs(ActivateRsType value) {
        return new JAXBElement<ActivateRsType>(_ActivateRs_QNAME, ActivateRsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustProfileInqRsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "CustProfileInqRs")
    public JAXBElement<CustProfileInqRsType> createCustProfileInqRs(CustProfileInqRsType value) {
        return new JAXBElement<CustProfileInqRsType>(_CustProfileInqRs_QNAME, CustProfileInqRsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetByKeyRsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "GetByKeyRs")
    public JAXBElement<GetByKeyRsType> createGetByKeyRs(GetByKeyRsType value) {
        return new JAXBElement<GetByKeyRsType>(_GetByKeyRs_QNAME, GetByKeyRsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetByKeyRqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "GetByKeyRq")
    public JAXBElement<GetByKeyRqType> createGetByKeyRq(GetByKeyRqType value) {
        return new JAXBElement<GetByKeyRqType>(_GetByKeyRq_QNAME, GetByKeyRqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountAssnStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "AccountAssnStatus")
    public JAXBElement<AccountAssnStatusType> createAccountAssnStatus(AccountAssnStatusType value) {
        return new JAXBElement<AccountAssnStatusType>(_AccountAssnStatus_QNAME, AccountAssnStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateRsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "DeactivateRs")
    public JAXBElement<DeactivateRsType> createDeactivateRs(DeactivateRsType value) {
        return new JAXBElement<DeactivateRsType>(_DeactivateRs_QNAME, DeactivateRsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateRqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "DeactivateRq")
    public JAXBElement<DeactivateRqType> createDeactivateRq(DeactivateRqType value) {
        return new JAXBElement<DeactivateRqType>(_DeactivateRq_QNAME, DeactivateRqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountAssnStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "AccountDisassnStatus")
    public JAXBElement<AccountAssnStatusType> createAccountDisassnStatus(AccountAssnStatusType value) {
        return new JAXBElement<AccountAssnStatusType>(_AccountDisassnStatus_QNAME, AccountAssnStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "IsInProfile")
    public JAXBElement<Boolean> createIsInProfile(Boolean value) {
        return new JAXBElement<Boolean>(_IsInProfile_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListByBillRsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "ListByBillRs")
    public JAXBElement<ListByBillRsType> createListByBillRs(ListByBillRsType value) {
        return new JAXBElement<ListByBillRsType>(_ListByBillRs_QNAME, ListByBillRsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListByBillRqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/EBPP/scm/schema/Customer/1.0", name = "ListByBillRq")
    public JAXBElement<ListByBillRqType> createListByBillRq(ListByBillRqType value) {
        return new JAXBElement<ListByBillRqType>(_ListByBillRq_QNAME, ListByBillRqType.class, null, value);
    }

}
