//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.scm.error._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sadad.scm.error._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Parameter_QNAME = new QName("http://www.sadad.com/scm/Error/1.0", "Parameter");
    private final static QName _Severity_QNAME = new QName("http://www.sadad.com/scm/Error/1.0", "Severity");
    private final static QName _Fault_QNAME = new QName("http://www.sadad.com/scm/Error/1.0", "Fault");
    private final static QName _Parameters_QNAME = new QName("http://www.sadad.com/scm/Error/1.0", "Parameters");
    private final static QName _Type_QNAME = new QName("http://www.sadad.com/scm/Error/1.0", "Type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sadad.scm.error._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FaultType }
     * 
     */
    public FaultType createFaultType() {
        return new FaultType();
    }

    /**
     * Create an instance of {@link ParametersType }
     * 
     */
    public ParametersType createParametersType() {
        return new ParametersType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/scm/Error/1.0", name = "Parameter")
    public JAXBElement<ParameterType> createParameter(ParameterType value) {
        return new JAXBElement<ParameterType>(_Parameter_QNAME, ParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SeverityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/scm/Error/1.0", name = "Severity")
    public JAXBElement<SeverityType> createSeverity(SeverityType value) {
        return new JAXBElement<SeverityType>(_Severity_QNAME, SeverityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/scm/Error/1.0", name = "Fault")
    public JAXBElement<FaultType> createFault(FaultType value) {
        return new JAXBElement<FaultType>(_Fault_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParametersType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/scm/Error/1.0", name = "Parameters")
    public JAXBElement<ParametersType> createParameters(ParametersType value) {
        return new JAXBElement<ParametersType>(_Parameters_QNAME, ParametersType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sadad.com/scm/Error/1.0", name = "Type")
    public JAXBElement<ErrorType> createType(ErrorType value) {
        return new JAXBElement<ErrorType>(_Type_QNAME, ErrorType.class, null, value);
    }

}
