//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.ebpp.wsdl.lookupservice._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.sadad.ebpp.schema.lookup._1.LookupRqType;
import com.sadad.ebpp.schema.lookup._1.LookupRsType;

@WebService(name = "LookupServicePort", targetNamespace = "http://www.sadad.com/EBPP/wsdl/LookupService/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.sadad.scm.common._1.ObjectFactory.class,
    com.sadad.ebpp.schema.lookup._1.ObjectFactory.class,
    com.sadad.scm.error._1.ObjectFactory.class,
    com.sadad.scm.common.system._1.ObjectFactory.class
})
public interface LookupServicePort {


    /**
     * 
     * @param lookupRq
     * @return
     *     returns com.sadad.ebpp.schema.lookup._1.LookupRsType
     * @throws LookupFault
     */
    @WebMethod(operationName = "Lookup")
    @WebResult(name = "LookupRs", targetNamespace = "http://www.sadad.com/EBPP/schema/Lookup/1.0", partName = "LookupRs")
    public LookupRsType lookup(
        @WebParam(name = "LookupRq", targetNamespace = "http://www.sadad.com/EBPP/schema/Lookup/1.0", partName = "LookupRq")
        LookupRqType lookupRq)
        throws LookupFault
    ;

}
