//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//

package com.sadad.ebpp.schema.referencedata._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.sadad.scm.error._1.FaultType;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the com.sadad.ebpp.schema.referencedata._1 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of
 * schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	private final static QName _DeactivateAccountTypeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "DeactivateAccountTypeRs");
	private final static QName _DeactivateAccountTypeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "DeactivateAccountTypeRq");
	private final static QName _UpdateDistrictCodeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "UpdateDistrictCodeRs");
	private final static QName _UpdateDistrictCodeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "UpdateDistrictCodeRq");
	private final static QName _CreateDistrictCodeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "CreateDistrictCodeRq");
	private final static QName _CreateDistrictCodeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "CreateDistrictCodeRs");
	private final static QName _ListAccessChannelRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ListAccessChannelRs");
	private final static QName _ListAccessChannelRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ListAccessChannelRq");
	private final static QName _AccessChannel_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "AccessChannel");
	private final static QName _ActivateDistrictCodeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ActivateDistrictCodeRq");
	private final static QName _ListPaymentMethodRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ListPaymentMethodRs");
	private final static QName _ActivateDistrictCodeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ActivateDistrictCodeRs");
	private final static QName _ListPaymentMethodRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ListPaymentMethodRq");
	private final static QName _CreatePaymentMethodRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "CreatePaymentMethodRq");
	private final static QName _ListDistrictCodeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ListDistrictCodeRq");
	private final static QName _CreatePaymentMethodRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "CreatePaymentMethodRs");
	private final static QName _ListDistrictCodeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ListDistrictCodeRs");
	private final static QName _DeactivatePaymentMethodRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "DeactivatePaymentMethodRq");
	private final static QName _DeactivatePaymentMethodRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "DeactivatePaymentMethodRs");
	private final static QName _DistrictCode_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "DistrictCode");
	private final static QName _UpdatePaymentMethodRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "UpdatePaymentMethodRq");
	private final static QName _UpdatePaymentMethodRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "UpdatePaymentMethodRs");
	private final static QName _GetAccessChannelRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "GetAccessChannelRs");
	private final static QName _GetAccessChannelRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "GetAccessChannelRq");
	private final static QName _CreateAccessChannelRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "CreateAccessChannelRs");
	private final static QName _DeactivateAccessChannelRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "DeactivateAccessChannelRs");
	private final static QName _CreateAccessChannelRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "CreateAccessChannelRq");
	private final static QName _DeactivateAccessChannelRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "DeactivateAccessChannelRq");
	private final static QName _ActivatePaymentMethodRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ActivatePaymentMethodRs");
	private final static QName _ActivatePaymentMethodRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ActivatePaymentMethodRq");
	private final static QName _GetAccountTypeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "GetAccountTypeRq");
	private final static QName _GetAccountTypeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "GetAccountTypeRs");
	private final static QName _UpdateAccessChannelRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "UpdateAccessChannelRq");
	private final static QName _ReferenceDataFault_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ReferenceDataFault");
	private final static QName _ActivateAccountTypeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ActivateAccountTypeRs");
	private final static QName _DeactivateDistrictCodeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "DeactivateDistrictCodeRq");
	private final static QName _UpdateAccountTypeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "UpdateAccountTypeRs");
	private final static QName _CreateAccountTypeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "CreateAccountTypeRq");
	private final static QName _ActivateAccountTypeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ActivateAccountTypeRq");
	private final static QName _DeactivateDistrictCodeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "DeactivateDistrictCodeRs");
	private final static QName _ActivateAccessChannelRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ActivateAccessChannelRq");
	private final static QName _CreateAccountTypeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "CreateAccountTypeRs");
	private final static QName _ActivateAccessChannelRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ActivateAccessChannelRs");
	private final static QName _UpdateAccountTypeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "UpdateAccountTypeRq");
	private final static QName _PaymentMethod_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "PaymentMethod");
	private final static QName _UpdateAccessChannelRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "UpdateAccessChannelRs");
	private final static QName _AccountType_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "AccountType");
	private final static QName _ListAccountTypeRq_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ListAccountTypeRq");
	private final static QName _ListAccountTypeRs_QNAME = new QName("http://www.sadad.com/EBPP/schema/ReferenceData/1.0", "ListAccountTypeRs");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sadad.ebpp.schema.referencedata._1
	 * 
	 */
	public ObjectFactory()
	{}

	/**
	 * Create an instance of {@link ActivateAccountTypeRqType }
	 * 
	 */
	public ActivateAccountTypeRqType createActivateAccountTypeRqType()
	{
		return new ActivateAccountTypeRqType();
	}

	/**
	 * Create an instance of {@link ActivateAccessChannelRsType }
	 * 
	 */
	public ActivateAccessChannelRsType createActivateAccessChannelRsType()
	{
		return new ActivateAccessChannelRsType();
	}

	/**
	 * Create an instance of {@link ActivateAccessChannelRqType }
	 * 
	 */
	public ActivateAccessChannelRqType createActivateAccessChannelRqType()
	{
		return new ActivateAccessChannelRqType();
	}

	/**
	 * Create an instance of {@link ActivateAccountTypeRsType }
	 * 
	 */
	public ActivateAccountTypeRsType createActivateAccountTypeRsType()
	{
		return new ActivateAccountTypeRsType();
	}

	/**
	 * Create an instance of {@link CreatePaymentMethodRqType }
	 * 
	 */
	public CreatePaymentMethodRqType createCreatePaymentMethodRqType()
	{
		return new CreatePaymentMethodRqType();
	}

	/**
	 * Create an instance of {@link DeactivatePaymentMethodRsType }
	 * 
	 */
	public DeactivatePaymentMethodRsType createDeactivatePaymentMethodRsType()
	{
		return new DeactivatePaymentMethodRsType();
	}

	/**
	 * Create an instance of {@link CreatePaymentMethodRsType }
	 * 
	 */
	public CreatePaymentMethodRsType createCreatePaymentMethodRsType()
	{
		return new CreatePaymentMethodRsType();
	}

	/**
	 * Create an instance of {@link DeactivatePaymentMethodRqType }
	 * 
	 */
	public DeactivatePaymentMethodRqType createDeactivatePaymentMethodRqType()
	{
		return new DeactivatePaymentMethodRqType();
	}

	/**
	 * Create an instance of {@link UpdatePaymentMethodRsType }
	 * 
	 */
	public UpdatePaymentMethodRsType createUpdatePaymentMethodRsType()
	{
		return new UpdatePaymentMethodRsType();
	}

	/**
	 * Create an instance of {@link ListAccountTypeRqType }
	 * 
	 */
	public ListAccountTypeRqType createListAccountTypeRqType()
	{
		return new ListAccountTypeRqType();
	}

	/**
	 * Create an instance of {@link UpdatePaymentMethodRqType }
	 * 
	 */
	public UpdatePaymentMethodRqType createUpdatePaymentMethodRqType()
	{
		return new UpdatePaymentMethodRqType();
	}

	/**
	 * Create an instance of {@link ListAccountTypeRsType }
	 * 
	 */
	public ListAccountTypeRsType createListAccountTypeRsType()
	{
		return new ListAccountTypeRsType();
	}

	/**
	 * Create an instance of {@link CreateAccountTypeRsType }
	 * 
	 */
	public CreateAccountTypeRsType createCreateAccountTypeRsType()
	{
		return new CreateAccountTypeRsType();
	}

	/**
	 * Create an instance of {@link CreateAccountTypeRqType }
	 * 
	 */
	public CreateAccountTypeRqType createCreateAccountTypeRqType()
	{
		return new CreateAccountTypeRqType();
	}

	/**
	 * Create an instance of {@link ActivateDistrictCodeRsType }
	 * 
	 */
	public ActivateDistrictCodeRsType createActivateDistrictCodeRsType()
	{
		return new ActivateDistrictCodeRsType();
	}

	/**
	 * Create an instance of {@link ActivateDistrictCodeRqType }
	 * 
	 */
	public ActivateDistrictCodeRqType createActivateDistrictCodeRqType()
	{
		return new ActivateDistrictCodeRqType();
	}

	/**
	 * Create an instance of {@link AccountTypeType }
	 * 
	 */
	public AccountTypeType createAccountTypeType()
	{
		return new AccountTypeType();
	}

	/**
	 * Create an instance of {@link DeactivateAccountTypeRqType }
	 * 
	 */
	public DeactivateAccountTypeRqType createDeactivateAccountTypeRqType()
	{
		return new DeactivateAccountTypeRqType();
	}

	/**
	 * Create an instance of {@link DeactivateAccountTypeRsType }
	 * 
	 */
	public DeactivateAccountTypeRsType createDeactivateAccountTypeRsType()
	{
		return new DeactivateAccountTypeRsType();
	}

	/**
	 * Create an instance of {@link DeactivateDistrictCodeRsType }
	 * 
	 */
	public DeactivateDistrictCodeRsType createDeactivateDistrictCodeRsType()
	{
		return new DeactivateDistrictCodeRsType();
	}

	/**
	 * Create an instance of {@link PaymentMethodType }
	 * 
	 */
	public PaymentMethodType createPaymentMethodType()
	{
		return new PaymentMethodType();
	}

	/**
	 * Create an instance of {@link CreateDistrictCodeRqType }
	 * 
	 */
	public CreateDistrictCodeRqType createCreateDistrictCodeRqType()
	{
		return new CreateDistrictCodeRqType();
	}

	/**
	 * Create an instance of {@link DeactivateDistrictCodeRqType }
	 * 
	 */
	public DeactivateDistrictCodeRqType createDeactivateDistrictCodeRqType()
	{
		return new DeactivateDistrictCodeRqType();
	}

	/**
	 * Create an instance of {@link ListPaymentMethodRqType }
	 * 
	 */
	public ListPaymentMethodRqType createListPaymentMethodRqType()
	{
		return new ListPaymentMethodRqType();
	}

	/**
	 * Create an instance of {@link ListPaymentMethodRsType }
	 * 
	 */
	public ListPaymentMethodRsType createListPaymentMethodRsType()
	{
		return new ListPaymentMethodRsType();
	}

	/**
	 * Create an instance of {@link CreateDistrictCodeRsType }
	 * 
	 */
	public CreateDistrictCodeRsType createCreateDistrictCodeRsType()
	{
		return new CreateDistrictCodeRsType();
	}

	/**
	 * Create an instance of {@link UpdateAccessChannelRsType }
	 * 
	 */
	public UpdateAccessChannelRsType createUpdateAccessChannelRsType()
	{
		return new UpdateAccessChannelRsType();
	}

	/**
	 * Create an instance of {@link AccessChannelType }
	 * 
	 */
	public AccessChannelType createAccessChannelType()
	{
		return new AccessChannelType();
	}

	/**
	 * Create an instance of {@link UpdateAccessChannelRqType }
	 * 
	 */
	public UpdateAccessChannelRqType createUpdateAccessChannelRqType()
	{
		return new UpdateAccessChannelRqType();
	}

	/**
	 * Create an instance of {@link DeactivateAccessChannelRsType }
	 * 
	 */
	public DeactivateAccessChannelRsType createDeactivateAccessChannelRsType()
	{
		return new DeactivateAccessChannelRsType();
	}

	/**
	 * Create an instance of {@link ListDistrictCodeRsType }
	 * 
	 */
	public ListDistrictCodeRsType createListDistrictCodeRsType()
	{
		return new ListDistrictCodeRsType();
	}

	/**
	 * Create an instance of {@link CreateAccessChannelRsType }
	 * 
	 */
	public CreateAccessChannelRsType createCreateAccessChannelRsType()
	{
		return new CreateAccessChannelRsType();
	}

	/**
	 * Create an instance of {@link ListDistrictCodeRqType }
	 * 
	 */
	public ListDistrictCodeRqType createListDistrictCodeRqType()
	{
		return new ListDistrictCodeRqType();
	}

	/**
	 * Create an instance of {@link CreateAccessChannelRqType }
	 * 
	 */
	public CreateAccessChannelRqType createCreateAccessChannelRqType()
	{
		return new CreateAccessChannelRqType();
	}

	/**
	 * Create an instance of {@link DeactivateAccessChannelRqType }
	 * 
	 */
	public DeactivateAccessChannelRqType createDeactivateAccessChannelRqType()
	{
		return new DeactivateAccessChannelRqType();
	}

	/**
	 * Create an instance of {@link DistrictCodeType }
	 * 
	 */
	public DistrictCodeType createDistrictCodeType()
	{
		return new DistrictCodeType();
	}

	/**
	 * Create an instance of {@link UpdateDistrictCodeRqType }
	 * 
	 */
	public UpdateDistrictCodeRqType createUpdateDistrictCodeRqType()
	{
		return new UpdateDistrictCodeRqType();
	}

	/**
	 * Create an instance of {@link UpdateDistrictCodeRsType }
	 * 
	 */
	public UpdateDistrictCodeRsType createUpdateDistrictCodeRsType()
	{
		return new UpdateDistrictCodeRsType();
	}

	/**
	 * Create an instance of {@link ListAccessChannelRsType }
	 * 
	 */
	public ListAccessChannelRsType createListAccessChannelRsType()
	{
		return new ListAccessChannelRsType();
	}

	/**
	 * Create an instance of {@link ListAccessChannelRqType }
	 * 
	 */
	public ListAccessChannelRqType createListAccessChannelRqType()
	{
		return new ListAccessChannelRqType();
	}

	/**
	 * Create an instance of {@link ActivatePaymentMethodRqType }
	 * 
	 */
	public ActivatePaymentMethodRqType createActivatePaymentMethodRqType()
	{
		return new ActivatePaymentMethodRqType();
	}

	/**
	 * Create an instance of {@link UpdateAccountTypeRsType }
	 * 
	 */
	public UpdateAccountTypeRsType createUpdateAccountTypeRsType()
	{
		return new UpdateAccountTypeRsType();
	}

	/**
	 * Create an instance of {@link ActivatePaymentMethodRsType }
	 * 
	 */
	public ActivatePaymentMethodRsType createActivatePaymentMethodRsType()
	{
		return new ActivatePaymentMethodRsType();
	}

	/**
	 * Create an instance of {@link UpdateAccountTypeRqType }
	 * 
	 */
	public UpdateAccountTypeRqType createUpdateAccountTypeRqType()
	{
		return new UpdateAccountTypeRqType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateAccountTypeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "DeactivateAccountTypeRs")
	public JAXBElement<DeactivateAccountTypeRsType> createDeactivateAccountTypeRs(DeactivateAccountTypeRsType value)
	{
		return new JAXBElement<DeactivateAccountTypeRsType>(_DeactivateAccountTypeRs_QNAME, DeactivateAccountTypeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateAccountTypeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "DeactivateAccountTypeRq")
	public JAXBElement<DeactivateAccountTypeRqType> createDeactivateAccountTypeRq(DeactivateAccountTypeRqType value)
	{
		return new JAXBElement<DeactivateAccountTypeRqType>(_DeactivateAccountTypeRq_QNAME, DeactivateAccountTypeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UpdateDistrictCodeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "UpdateDistrictCodeRs")
	public JAXBElement<UpdateDistrictCodeRsType> createUpdateDistrictCodeRs(UpdateDistrictCodeRsType value)
	{
		return new JAXBElement<UpdateDistrictCodeRsType>(_UpdateDistrictCodeRs_QNAME, UpdateDistrictCodeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UpdateDistrictCodeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "UpdateDistrictCodeRq")
	public JAXBElement<UpdateDistrictCodeRqType> createUpdateDistrictCodeRq(UpdateDistrictCodeRqType value)
	{
		return new JAXBElement<UpdateDistrictCodeRqType>(_UpdateDistrictCodeRq_QNAME, UpdateDistrictCodeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CreateDistrictCodeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "CreateDistrictCodeRq")
	public JAXBElement<CreateDistrictCodeRqType> createCreateDistrictCodeRq(CreateDistrictCodeRqType value)
	{
		return new JAXBElement<CreateDistrictCodeRqType>(_CreateDistrictCodeRq_QNAME, CreateDistrictCodeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CreateDistrictCodeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "CreateDistrictCodeRs")
	public JAXBElement<CreateDistrictCodeRsType> createCreateDistrictCodeRs(CreateDistrictCodeRsType value)
	{
		return new JAXBElement<CreateDistrictCodeRsType>(_CreateDistrictCodeRs_QNAME, CreateDistrictCodeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListAccessChannelRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ListAccessChannelRs")
	public JAXBElement<ListAccessChannelRsType> createListAccessChannelRs(ListAccessChannelRsType value)
	{
		return new JAXBElement<ListAccessChannelRsType>(_ListAccessChannelRs_QNAME, ListAccessChannelRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListAccessChannelRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ListAccessChannelRq")
	public JAXBElement<ListAccessChannelRqType> createListAccessChannelRq(ListAccessChannelRqType value)
	{
		return new JAXBElement<ListAccessChannelRqType>(_ListAccessChannelRq_QNAME, ListAccessChannelRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AccessChannelType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "AccessChannel")
	public JAXBElement<AccessChannelType> createAccessChannel(AccessChannelType value)
	{
		return new JAXBElement<AccessChannelType>(_AccessChannel_QNAME, AccessChannelType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ActivateDistrictCodeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ActivateDistrictCodeRq")
	public JAXBElement<ActivateDistrictCodeRqType> createActivateDistrictCodeRq(ActivateDistrictCodeRqType value)
	{
		return new JAXBElement<ActivateDistrictCodeRqType>(_ActivateDistrictCodeRq_QNAME, ActivateDistrictCodeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListPaymentMethodRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ListPaymentMethodRs")
	public JAXBElement<ListPaymentMethodRsType> createListPaymentMethodRs(ListPaymentMethodRsType value)
	{
		return new JAXBElement<ListPaymentMethodRsType>(_ListPaymentMethodRs_QNAME, ListPaymentMethodRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ActivateDistrictCodeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ActivateDistrictCodeRs")
	public JAXBElement<ActivateDistrictCodeRsType> createActivateDistrictCodeRs(ActivateDistrictCodeRsType value)
	{
		return new JAXBElement<ActivateDistrictCodeRsType>(_ActivateDistrictCodeRs_QNAME, ActivateDistrictCodeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListPaymentMethodRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ListPaymentMethodRq")
	public JAXBElement<ListPaymentMethodRqType> createListPaymentMethodRq(ListPaymentMethodRqType value)
	{
		return new JAXBElement<ListPaymentMethodRqType>(_ListPaymentMethodRq_QNAME, ListPaymentMethodRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CreatePaymentMethodRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "CreatePaymentMethodRq")
	public JAXBElement<CreatePaymentMethodRqType> createCreatePaymentMethodRq(CreatePaymentMethodRqType value)
	{
		return new JAXBElement<CreatePaymentMethodRqType>(_CreatePaymentMethodRq_QNAME, CreatePaymentMethodRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListDistrictCodeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ListDistrictCodeRq")
	public JAXBElement<ListDistrictCodeRqType> createListDistrictCodeRq(ListDistrictCodeRqType value)
	{
		return new JAXBElement<ListDistrictCodeRqType>(_ListDistrictCodeRq_QNAME, ListDistrictCodeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CreatePaymentMethodRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "CreatePaymentMethodRs")
	public JAXBElement<CreatePaymentMethodRsType> createCreatePaymentMethodRs(CreatePaymentMethodRsType value)
	{
		return new JAXBElement<CreatePaymentMethodRsType>(_CreatePaymentMethodRs_QNAME, CreatePaymentMethodRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListDistrictCodeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ListDistrictCodeRs")
	public JAXBElement<ListDistrictCodeRsType> createListDistrictCodeRs(ListDistrictCodeRsType value)
	{
		return new JAXBElement<ListDistrictCodeRsType>(_ListDistrictCodeRs_QNAME, ListDistrictCodeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DeactivatePaymentMethodRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "DeactivatePaymentMethodRq")
	public JAXBElement<DeactivatePaymentMethodRqType> createDeactivatePaymentMethodRq(DeactivatePaymentMethodRqType value)
	{
		return new JAXBElement<DeactivatePaymentMethodRqType>(_DeactivatePaymentMethodRq_QNAME, DeactivatePaymentMethodRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DeactivatePaymentMethodRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "DeactivatePaymentMethodRs")
	public JAXBElement<DeactivatePaymentMethodRsType> createDeactivatePaymentMethodRs(DeactivatePaymentMethodRsType value)
	{
		return new JAXBElement<DeactivatePaymentMethodRsType>(_DeactivatePaymentMethodRs_QNAME, DeactivatePaymentMethodRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DistrictCodeType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "DistrictCode")
	public JAXBElement<DistrictCodeType> createDistrictCode(DistrictCodeType value)
	{
		return new JAXBElement<DistrictCodeType>(_DistrictCode_QNAME, DistrictCodeType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePaymentMethodRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "UpdatePaymentMethodRq")
	public JAXBElement<UpdatePaymentMethodRqType> createUpdatePaymentMethodRq(UpdatePaymentMethodRqType value)
	{
		return new JAXBElement<UpdatePaymentMethodRqType>(_UpdatePaymentMethodRq_QNAME, UpdatePaymentMethodRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePaymentMethodRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "UpdatePaymentMethodRs")
	public JAXBElement<UpdatePaymentMethodRsType> createUpdatePaymentMethodRs(UpdatePaymentMethodRsType value)
	{
		return new JAXBElement<UpdatePaymentMethodRsType>(_UpdatePaymentMethodRs_QNAME, UpdatePaymentMethodRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListAccessChannelRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "GetAccessChannelRs")
	public JAXBElement<ListAccessChannelRsType> createGetAccessChannelRs(ListAccessChannelRsType value)
	{
		return new JAXBElement<ListAccessChannelRsType>(_GetAccessChannelRs_QNAME, ListAccessChannelRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListAccessChannelRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "GetAccessChannelRq")
	public JAXBElement<ListAccessChannelRqType> createGetAccessChannelRq(ListAccessChannelRqType value)
	{
		return new JAXBElement<ListAccessChannelRqType>(_GetAccessChannelRq_QNAME, ListAccessChannelRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccessChannelRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "CreateAccessChannelRs")
	public JAXBElement<CreateAccessChannelRsType> createCreateAccessChannelRs(CreateAccessChannelRsType value)
	{
		return new JAXBElement<CreateAccessChannelRsType>(_CreateAccessChannelRs_QNAME, CreateAccessChannelRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateAccessChannelRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "DeactivateAccessChannelRs")
	public JAXBElement<DeactivateAccessChannelRsType> createDeactivateAccessChannelRs(DeactivateAccessChannelRsType value)
	{
		return new JAXBElement<DeactivateAccessChannelRsType>(_DeactivateAccessChannelRs_QNAME, DeactivateAccessChannelRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccessChannelRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "CreateAccessChannelRq")
	public JAXBElement<CreateAccessChannelRqType> createCreateAccessChannelRq(CreateAccessChannelRqType value)
	{
		return new JAXBElement<CreateAccessChannelRqType>(_CreateAccessChannelRq_QNAME, CreateAccessChannelRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateAccessChannelRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "DeactivateAccessChannelRq")
	public JAXBElement<DeactivateAccessChannelRqType> createDeactivateAccessChannelRq(DeactivateAccessChannelRqType value)
	{
		return new JAXBElement<DeactivateAccessChannelRqType>(_DeactivateAccessChannelRq_QNAME, DeactivateAccessChannelRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ActivatePaymentMethodRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ActivatePaymentMethodRs")
	public JAXBElement<ActivatePaymentMethodRsType> createActivatePaymentMethodRs(ActivatePaymentMethodRsType value)
	{
		return new JAXBElement<ActivatePaymentMethodRsType>(_ActivatePaymentMethodRs_QNAME, ActivatePaymentMethodRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ActivatePaymentMethodRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ActivatePaymentMethodRq")
	public JAXBElement<ActivatePaymentMethodRqType> createActivatePaymentMethodRq(ActivatePaymentMethodRqType value)
	{
		return new JAXBElement<ActivatePaymentMethodRqType>(_ActivatePaymentMethodRq_QNAME, ActivatePaymentMethodRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListAccountTypeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "GetAccountTypeRq")
	public JAXBElement<ListAccountTypeRqType> createGetAccountTypeRq(ListAccountTypeRqType value)
	{
		return new JAXBElement<ListAccountTypeRqType>(_GetAccountTypeRq_QNAME, ListAccountTypeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListAccountTypeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "GetAccountTypeRs")
	public JAXBElement<ListAccountTypeRsType> createGetAccountTypeRs(ListAccountTypeRsType value)
	{
		return new JAXBElement<ListAccountTypeRsType>(_GetAccountTypeRs_QNAME, ListAccountTypeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAccessChannelRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "UpdateAccessChannelRq")
	public JAXBElement<UpdateAccessChannelRqType> createUpdateAccessChannelRq(UpdateAccessChannelRqType value)
	{
		return new JAXBElement<UpdateAccessChannelRqType>(_UpdateAccessChannelRq_QNAME, UpdateAccessChannelRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ReferenceDataFault")
	public JAXBElement<FaultType> createReferenceDataFault(FaultType value)
	{
		return new JAXBElement<FaultType>(_ReferenceDataFault_QNAME, FaultType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ActivateAccountTypeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ActivateAccountTypeRs")
	public JAXBElement<ActivateAccountTypeRsType> createActivateAccountTypeRs(ActivateAccountTypeRsType value)
	{
		return new JAXBElement<ActivateAccountTypeRsType>(_ActivateAccountTypeRs_QNAME, ActivateAccountTypeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateDistrictCodeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "DeactivateDistrictCodeRq")
	public JAXBElement<DeactivateDistrictCodeRqType> createDeactivateDistrictCodeRq(DeactivateDistrictCodeRqType value)
	{
		return new JAXBElement<DeactivateDistrictCodeRqType>(_DeactivateDistrictCodeRq_QNAME, DeactivateDistrictCodeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAccountTypeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "UpdateAccountTypeRs")
	public JAXBElement<UpdateAccountTypeRsType> createUpdateAccountTypeRs(UpdateAccountTypeRsType value)
	{
		return new JAXBElement<UpdateAccountTypeRsType>(_UpdateAccountTypeRs_QNAME, UpdateAccountTypeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountTypeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "CreateAccountTypeRq")
	public JAXBElement<CreateAccountTypeRqType> createCreateAccountTypeRq(CreateAccountTypeRqType value)
	{
		return new JAXBElement<CreateAccountTypeRqType>(_CreateAccountTypeRq_QNAME, CreateAccountTypeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ActivateAccountTypeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ActivateAccountTypeRq")
	public JAXBElement<ActivateAccountTypeRqType> createActivateAccountTypeRq(ActivateAccountTypeRqType value)
	{
		return new JAXBElement<ActivateAccountTypeRqType>(_ActivateAccountTypeRq_QNAME, ActivateAccountTypeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateDistrictCodeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "DeactivateDistrictCodeRs")
	public JAXBElement<DeactivateDistrictCodeRsType> createDeactivateDistrictCodeRs(DeactivateDistrictCodeRsType value)
	{
		return new JAXBElement<DeactivateDistrictCodeRsType>(_DeactivateDistrictCodeRs_QNAME, DeactivateDistrictCodeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ActivateAccessChannelRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ActivateAccessChannelRq")
	public JAXBElement<ActivateAccessChannelRqType> createActivateAccessChannelRq(ActivateAccessChannelRqType value)
	{
		return new JAXBElement<ActivateAccessChannelRqType>(_ActivateAccessChannelRq_QNAME, ActivateAccessChannelRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountTypeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "CreateAccountTypeRs")
	public JAXBElement<CreateAccountTypeRsType> createCreateAccountTypeRs(CreateAccountTypeRsType value)
	{
		return new JAXBElement<CreateAccountTypeRsType>(_CreateAccountTypeRs_QNAME, CreateAccountTypeRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ActivateAccessChannelRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ActivateAccessChannelRs")
	public JAXBElement<ActivateAccessChannelRsType> createActivateAccessChannelRs(ActivateAccessChannelRsType value)
	{
		return new JAXBElement<ActivateAccessChannelRsType>(_ActivateAccessChannelRs_QNAME, ActivateAccessChannelRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAccountTypeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "UpdateAccountTypeRq")
	public JAXBElement<UpdateAccountTypeRqType> createUpdateAccountTypeRq(UpdateAccountTypeRqType value)
	{
		return new JAXBElement<UpdateAccountTypeRqType>(_UpdateAccountTypeRq_QNAME, UpdateAccountTypeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link PaymentMethodType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "PaymentMethod")
	public JAXBElement<PaymentMethodType> createPaymentMethod(PaymentMethodType value)
	{
		return new JAXBElement<PaymentMethodType>(_PaymentMethod_QNAME, PaymentMethodType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAccessChannelRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "UpdateAccessChannelRs")
	public JAXBElement<UpdateAccessChannelRsType> createUpdateAccessChannelRs(UpdateAccessChannelRsType value)
	{
		return new JAXBElement<UpdateAccessChannelRsType>(_UpdateAccessChannelRs_QNAME, UpdateAccessChannelRsType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link AccountTypeType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "AccountType")
	public JAXBElement<AccountTypeType> createAccountType(AccountTypeType value)
	{
		return new JAXBElement<AccountTypeType>(_AccountType_QNAME, AccountTypeType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListAccountTypeRqType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ListAccountTypeRq")
	public JAXBElement<ListAccountTypeRqType> createListAccountTypeRq(ListAccountTypeRqType value)
	{
		return new JAXBElement<ListAccountTypeRqType>(_ListAccountTypeRq_QNAME, ListAccountTypeRqType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ListAccountTypeRsType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.sadad.com/EBPP/schema/ReferenceData/1.0", name = "ListAccountTypeRs")
	public JAXBElement<ListAccountTypeRsType> createListAccountTypeRs(ListAccountTypeRsType value)
	{
		return new JAXBElement<ListAccountTypeRsType>(_ListAccountTypeRs_QNAME, ListAccountTypeRsType.class, null, value);
	}

}
