//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.ebpp.scm.schema.partnerprofileservice._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.sadad.scm.common._1.BaseType;
import com.sadad.scm.common._1.PartnerTypeEnums;
import com.sadad.scm.common._1.ServiceMsgTypeSType;
import com.sadad.scm.common._1.SubscribedSType;


/**
 * <p>Java class for GetSubscribedServiceRequest_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetSubscribedServiceRequest_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sadad.com/scm/Common/1.0}BaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}PartnerKey"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}PartnerType"/>
 *         &lt;element ref="{http://www.sadad.com/EBPP/scm/schema/PartnerProfileService/1.0}ServiceID"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}Version" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}Subscribed" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}ServiceMsgType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetSubscribedServiceRequest_Type", propOrder = {
    "partnerKey",
    "partnerType",
    "serviceID",
    "version",
    "subscribed",
    "serviceMsgType"
})
public class GetSubscribedServiceRequestType
    extends BaseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "PartnerKey", namespace = "http://www.sadad.com/scm/Common/1.0", required = true)
    protected String partnerKey;
    @XmlElement(name = "PartnerType", namespace = "http://www.sadad.com/scm/Common/1.0", required = true)
    protected PartnerTypeEnums partnerType;
    @XmlElement(name = "ServiceID", required = true)
    protected String serviceID;
    @XmlElement(name = "Version", namespace = "http://www.sadad.com/scm/Common/1.0", defaultValue = "1.0")
    protected String version;
    @XmlElement(name = "Subscribed", namespace = "http://www.sadad.com/scm/Common/1.0")
    protected SubscribedSType subscribed;
    @XmlElement(name = "ServiceMsgType", namespace = "http://www.sadad.com/scm/Common/1.0", defaultValue = "XML")
    protected ServiceMsgTypeSType serviceMsgType;

    /**
     * Gets the value of the partnerKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerKey() {
        return partnerKey;
    }

    /**
     * Sets the value of the partnerKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerKey(String value) {
        this.partnerKey = value;
    }

    /**
     * Gets the value of the partnerType property.
     * 
     * @return
     *     possible object is
     *     {@link PartnerTypeEnums }
     *     
     */
    public PartnerTypeEnums getPartnerType() {
        return partnerType;
    }

    /**
     * Sets the value of the partnerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnerTypeEnums }
     *     
     */
    public void setPartnerType(PartnerTypeEnums value) {
        this.partnerType = value;
    }

    /**
     * Gets the value of the serviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceID() {
        return serviceID;
    }

    /**
     * Sets the value of the serviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceID(String value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the subscribed property.
     * 
     * @return
     *     possible object is
     *     {@link SubscribedSType }
     *     
     */
    public SubscribedSType getSubscribed() {
        return subscribed;
    }

    /**
     * Sets the value of the subscribed property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscribedSType }
     *     
     */
    public void setSubscribed(SubscribedSType value) {
        this.subscribed = value;
    }

    /**
     * Gets the value of the serviceMsgType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceMsgTypeSType }
     *     
     */
    public ServiceMsgTypeSType getServiceMsgType() {
        return serviceMsgType;
    }

    /**
     * Sets the value of the serviceMsgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceMsgTypeSType }
     *     
     */
    public void setServiceMsgType(ServiceMsgTypeSType value) {
        this.serviceMsgType = value;
    }

}
