//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.ebpp.scm.schema.partnerprofileservice._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.sadad.scm.common._1.BaseType;
import com.sadad.scm.common._1.SADADDetailType;


/**
 * <p>Java class for GetSADADResponse_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetSADADResponse_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sadad.com/scm/Common/1.0}BaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}SADADDetail"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetSADADResponse_Type", propOrder = {
    "sadadDetail"
})
public class GetSADADResponseType
    extends BaseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SADADDetail", namespace = "http://www.sadad.com/scm/Common/1.0", required = true)
    protected SADADDetailType sadadDetail;

    /**
     * Gets the value of the sadadDetail property.
     * 
     * @return
     *     possible object is
     *     {@link SADADDetailType }
     *     
     */
    public SADADDetailType getSADADDetail() {
        return sadadDetail;
    }

    /**
     * Sets the value of the sadadDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SADADDetailType }
     *     
     */
    public void setSADADDetail(SADADDetailType value) {
        this.sadadDetail = value;
    }

}
