//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sadad.ebpp.wsdl.partnerconfigurationservice._1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "PartnerConfigurationService", targetNamespace = "http://www.sadad.com/EBPP/wsdl/PartnerConfigurationService/1.0", wsdlLocation = "META-INF/wsdl/PartnerConfigurationService.wsdl")
public class PartnerConfigurationService_Service
    extends Service
{

    private final static URL PARTNERCONFIGURATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARTNERCONFIGURATIONSERVICE_EXCEPTION;
    private final static QName PARTNERCONFIGURATIONSERVICE_QNAME = new QName("http://www.sadad.com/EBPP/wsdl/PartnerConfigurationService/1.0", "PartnerConfigurationService");

    static {
            PARTNERCONFIGURATIONSERVICE_WSDL_LOCATION = com.sadad.ebpp.wsdl.partnerconfigurationservice._1.PartnerConfigurationService_Service.class.getResource("/META-INF/wsdl/PartnerConfigurationService.wsdl");
        WebServiceException e = null;
        if (PARTNERCONFIGURATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/PartnerConfigurationService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PARTNERCONFIGURATIONSERVICE_EXCEPTION = e;
    }

    public PartnerConfigurationService_Service() {
        super(__getWsdlLocation(), PARTNERCONFIGURATIONSERVICE_QNAME);
    }

    public PartnerConfigurationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARTNERCONFIGURATIONSERVICE_QNAME, features);
    }

    public PartnerConfigurationService_Service(URL wsdlLocation) {
        super(wsdlLocation, PARTNERCONFIGURATIONSERVICE_QNAME);
    }

    public PartnerConfigurationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARTNERCONFIGURATIONSERVICE_QNAME, features);
    }

    public PartnerConfigurationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PartnerConfigurationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PartnerConfigurationService
     */
    @WebEndpoint(name = "PartnerConfigurationServiceSOAP")
    public PartnerConfigurationService getPartnerConfigurationServiceSOAP() {
        return super.getPort(new QName("http://www.sadad.com/EBPP/wsdl/PartnerConfigurationService/1.0", "PartnerConfigurationServiceSOAP"), PartnerConfigurationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PartnerConfigurationService
     */
    @WebEndpoint(name = "PartnerConfigurationServiceSOAP")
    public PartnerConfigurationService getPartnerConfigurationServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sadad.com/EBPP/wsdl/PartnerConfigurationService/1.0", "PartnerConfigurationServiceSOAP"), PartnerConfigurationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARTNERCONFIGURATIONSERVICE_EXCEPTION!= null) {
            throw PARTNERCONFIGURATIONSERVICE_EXCEPTION;
        }
        return PARTNERCONFIGURATIONSERVICE_WSDL_LOCATION;
    }

}
