//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//

package com.sadad.schema.service.refundsearch._1;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.sadad.scm.common._1.BaseType;

/**
 * <p>
 * Java class for ListRefundRq_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListRefundRq_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sadad.com/scm/Common/1.0}BaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BankKey" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BillerKey" minOccurs="0"/>
 *         &lt;element name="FromDate" type="{http://www.sadad.com/scm/Common/System/1.0}Date_SType"/>
 *         &lt;element name="ToDate" type="{http://www.sadad.com/scm/Common/System/1.0}Date_SType"/>
 *         &lt;choice>
 *           &lt;element name="RefundStatus" type="{http://www.sadad.com/scm/Common/System/1.0}NC32_SType"/>
 *           &lt;element name="NotifyStatus" type="{http://www.sadad.com/scm/Common/System/1.0}NC32_SType"/>
 *           &lt;element name="ReconStatus" type="{http://www.sadad.com/scm/Common/System/1.0}NC32_SType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListRefundRq_Type", propOrder = { "bankKey", "billerKey", "fromDate", "toDate", "refundStatus", "notifyStatus", "reconStatus" })
public class ListRefundRqType extends BaseType implements Serializable
{

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "BankKey", namespace = "http://www.sadad.com/scm/Common/1.0")
	protected String bankKey;
	@XmlElement(name = "BillerKey", namespace = "http://www.sadad.com/scm/Common/1.0")
	protected String billerKey;
	@XmlElement(name = "FromDate", required = true)
	protected XMLGregorianCalendar fromDate;
	@XmlElement(name = "ToDate", required = true)
	protected XMLGregorianCalendar toDate;
	@XmlElement(name = "RefundStatus")
	protected String refundStatus;
	@XmlElement(name = "NotifyStatus")
	protected String notifyStatus;
	@XmlElement(name = "ReconStatus")
	protected String reconStatus;

	/**
	 * Gets the value of the bankKey property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBankKey()
	{
		return bankKey;
	}

	/**
	 * Sets the value of the bankKey property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBankKey(String value)
	{
		this.bankKey = value;
	}

	/**
	 * Gets the value of the billerKey property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBillerKey()
	{
		return billerKey;
	}

	/**
	 * Sets the value of the billerKey property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBillerKey(String value)
	{
		this.billerKey = value;
	}

	/**
	 * Gets the value of the fromDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFromDate()
	{
		return fromDate;
	}

	/**
	 * Sets the value of the fromDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFromDate(XMLGregorianCalendar value)
	{
		this.fromDate = value;
	}

	/**
	 * Gets the value of the toDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getToDate()
	{
		return toDate;
	}

	/**
	 * Sets the value of the toDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setToDate(XMLGregorianCalendar value)
	{
		this.toDate = value;
	}

	/**
	 * Gets the value of the refundStatus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRefundStatus()
	{
		return refundStatus;
	}

	/**
	 * Sets the value of the refundStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRefundStatus(String value)
	{
		this.refundStatus = value;
	}

	/**
	 * Gets the value of the notifyStatus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNotifyStatus()
	{
		return notifyStatus;
	}

	/**
	 * Sets the value of the notifyStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNotifyStatus(String value)
	{
		this.notifyStatus = value;
	}

	/**
	 * Gets the value of the reconStatus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReconStatus()
	{
		return reconStatus;
	}

	/**
	 * Sets the value of the reconStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReconStatus(String value)
	{
		this.reconStatus = value;
	}

}
