//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.sadad.schema.service.corepayment._1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.sadad.scm.common._1.BaseType;
import com.sadad.scm.common._1.CustIdCType;
import com.sadad.scm.common._1.DateRangeCType;


/**
 * <p>Java class for ListByPayorRq_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListByPayorRq_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sadad.com/scm/Common/1.0}BaseType">
 *       &lt;sequence>
 *         &lt;element name="Payor" type="{http://www.sadad.com/scm/Common/1.0}CustId_CType"/>
 *         &lt;element name="Billers" type="{http://sadad.com/schema/service/CorePayment/1.0}Billers_Type" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}BankKey" minOccurs="0"/>
 *         &lt;element name="Beneficiary" type="{http://www.sadad.com/scm/Common/1.0}CustId_CType" minOccurs="0"/>
 *         &lt;element ref="{http://www.sadad.com/scm/Common/1.0}Page" minOccurs="0"/>
 *         &lt;element name="DateRange" type="{http://www.sadad.com/scm/Common/1.0}DateRange_CType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListByPayorRq_Type", propOrder = {
    "payor",
    "billers",
    "bankKey",
    "beneficiary",
    "page",
    "dateRange"
})
public class ListByPayorRqType
    extends BaseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Payor", required = true)
    protected CustIdCType payor;
    @XmlElement(name = "Billers")
    protected BillersType billers;
    @XmlElement(name = "BankKey", namespace = "http://www.sadad.com/scm/Common/1.0")
    protected String bankKey;
    @XmlElement(name = "Beneficiary")
    protected CustIdCType beneficiary;
    @XmlElement(name = "Page", namespace = "http://www.sadad.com/scm/Common/1.0")
    protected Integer page;
    @XmlElement(name = "DateRange")
    protected DateRangeCType dateRange;

    /**
     * Gets the value of the payor property.
     * 
     * @return
     *     possible object is
     *     {@link CustIdCType }
     *     
     */
    public CustIdCType getPayor() {
        return payor;
    }

    /**
     * Sets the value of the payor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustIdCType }
     *     
     */
    public void setPayor(CustIdCType value) {
        this.payor = value;
    }

    /**
     * Gets the value of the billers property.
     * 
     * @return
     *     possible object is
     *     {@link BillersType }
     *     
     */
    public BillersType getBillers() {
        return billers;
    }

    /**
     * Sets the value of the billers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillersType }
     *     
     */
    public void setBillers(BillersType value) {
        this.billers = value;
    }

    /**
     * Gets the value of the bankKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankKey() {
        return bankKey;
    }

    /**
     * Sets the value of the bankKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankKey(String value) {
        this.bankKey = value;
    }

    /**
     * Gets the value of the beneficiary property.
     * 
     * @return
     *     possible object is
     *     {@link CustIdCType }
     *     
     */
    public CustIdCType getBeneficiary() {
        return beneficiary;
    }

    /**
     * Sets the value of the beneficiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustIdCType }
     *     
     */
    public void setBeneficiary(CustIdCType value) {
        this.beneficiary = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPage(Integer value) {
        this.page = value;
    }

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link DateRangeCType }
     *     
     */
    public DateRangeCType getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateRangeCType }
     *     
     */
    public void setDateRange(DateRangeCType value) {
        this.dateRange = value;
    }

}
